// Decompiled by Jad v1.5.8g. Copyright 2001 Pavel Kouznetsov.
// Jad home page: http://www.kpdus.com/jad.html
// Decompiler options: packimports(3) fieldsfirst noctor space 

package org.alljoyn.bus;


public final class Status extends Enum
{

    private static final Status $VALUES[];
    public static final Status ALERTED_THREAD;
    public static final Status ALLJOYN_ACCESS_PERMISSION_ERROR;
    public static final Status ALLJOYN_ACCESS_PERMISSION_WARNING;
    public static final Status ALLJOYN_ADVERTISENAME_REPLY_ALREADY_ADVERTISING;
    public static final Status ALLJOYN_ADVERTISENAME_REPLY_FAILED;
    public static final Status ALLJOYN_BINDSESSIONPORT_REPLY_ALREADY_EXISTS;
    public static final Status ALLJOYN_BINDSESSIONPORT_REPLY_FAILED;
    public static final Status ALLJOYN_BINDSESSIONPORT_REPLY_INVALID_OPTS;
    public static final Status ALLJOYN_CANCELADVERTISENAME_REPLY_FAILED;
    public static final Status ALLJOYN_CANCELFINDADVERTISEDNAME_REPLY_FAILED;
    public static final Status ALLJOYN_FINDADVERTISEDNAME_REPLY_ALREADY_DISCOVERING;
    public static final Status ALLJOYN_FINDADVERTISEDNAME_REPLY_FAILED;
    public static final Status ALLJOYN_JOINSESSION_REPLY_ALREADY_JOINED;
    public static final Status ALLJOYN_JOINSESSION_REPLY_BAD_SESSION_OPTS;
    public static final Status ALLJOYN_JOINSESSION_REPLY_CONNECT_FAILED;
    public static final Status ALLJOYN_JOINSESSION_REPLY_FAILED;
    public static final Status ALLJOYN_JOINSESSION_REPLY_NO_SESSION;
    public static final Status ALLJOYN_JOINSESSION_REPLY_REJECTED;
    public static final Status ALLJOYN_JOINSESSION_REPLY_UNREACHABLE;
    public static final Status ALLJOYN_LEAVESESSION_REPLY_FAILED;
    public static final Status ALLJOYN_LEAVESESSION_REPLY_NO_SESSION;
    public static final Status ALLJOYN_ONAPPRESUME_REPLY_FAILED;
    public static final Status ALLJOYN_ONAPPRESUME_REPLY_UNSUPPORTED;
    public static final Status ALLJOYN_ONAPPSUSPEND_REPLY_FAILED;
    public static final Status ALLJOYN_ONAPPSUSPEND_REPLY_UNSUPPORTED;
    public static final Status ALLJOYN_REMOVESESSIONMEMBER_INCOMPATIBLE_REMOTE_DAEMON;
    public static final Status ALLJOYN_REMOVESESSIONMEMBER_NOT_BINDER;
    public static final Status ALLJOYN_REMOVESESSIONMEMBER_NOT_FOUND;
    public static final Status ALLJOYN_REMOVESESSIONMEMBER_NOT_MULTIPOINT;
    public static final Status ALLJOYN_REMOVESESSIONMEMBER_REPLY_FAILED;
    public static final Status ALLJOYN_REMOVESESSIONMEMBER_REPLY_NO_SESSION;
    public static final Status ALLJOYN_SETLINKTIMEOUT_REPLY_FAILED;
    public static final Status ALLJOYN_SETLINKTIMEOUT_REPLY_NOT_SUPPORTED;
    public static final Status ALLJOYN_SETLINKTIMEOUT_REPLY_NO_DEST_SUPPORT;
    public static final Status ALLJOYN_UNBINDSESSIONPORT_REPLY_BAD_PORT;
    public static final Status ALLJOYN_UNBINDSESSIONPORT_REPLY_FAILED;
    public static final Status ALREADY_FINDING;
    public static final Status ALREADY_REGISTERED;
    public static final Status AUTH_FAIL;
    public static final Status AUTH_USER_REJECT;
    public static final Status BAD_ANNOTATION;
    public static final Status BAD_ARG_1;
    public static final Status BAD_ARG_2;
    public static final Status BAD_ARG_3;
    public static final Status BAD_ARG_4;
    public static final Status BAD_ARG_5;
    public static final Status BAD_ARG_6;
    public static final Status BAD_ARG_7;
    public static final Status BAD_ARG_8;
    public static final Status BAD_ARG_COUNT;
    public static final Status BAD_HOSTNAME;
    public static final Status BAD_STRING_ENCODING;
    public static final Status BAD_TRANSPORT_MASK;
    public static final Status BT_MAX_CONNECTIONS_USED;
    public static final Status BUFFER_TOO_SMALL;
    public static final Status BUS_ALREADY_CONNECTED;
    public static final Status BUS_ALREADY_LISTENING;
    public static final Status BUS_ANNOTATION_ALREADY_EXISTS;
    public static final Status BUS_AUTHENTICATION_PENDING;
    public static final Status BUS_BAD_BODY_LEN;
    public static final Status BUS_BAD_BUS_NAME;
    public static final Status BUS_BAD_CHILD_PATH;
    public static final Status BUS_BAD_ERROR_NAME;
    public static final Status BUS_BAD_HDR_FLAGS;
    public static final Status BUS_BAD_HEADER_FIELD;
    public static final Status BUS_BAD_HEADER_LEN;
    public static final Status BUS_BAD_INTERFACE_NAME;
    public static final Status BUS_BAD_LENGTH;
    public static final Status BUS_BAD_MEMBER_NAME;
    public static final Status BUS_BAD_OBJ_PATH;
    public static final Status BUS_BAD_SENDER_ID;
    public static final Status BUS_BAD_SEND_PARAMETER;
    public static final Status BUS_BAD_SESSION_OPTS;
    public static final Status BUS_BAD_SIGNATURE;
    public static final Status BUS_BAD_TRANSPORT_ARGS;
    public static final Status BUS_BAD_VALUE;
    public static final Status BUS_BAD_VALUE_TYPE;
    public static final Status BUS_BAD_XML;
    public static final Status BUS_BLOCKING_CALL_NOT_ALLOWED;
    public static final Status BUS_BT_TRANSPORT_ERROR;
    public static final Status BUS_BUS_ALREADY_STARTED;
    public static final Status BUS_BUS_NOT_STARTED;
    public static final Status BUS_CANNOT_ADD_HANDLER;
    public static final Status BUS_CANNOT_ADD_INTERFACE;
    public static final Status BUS_CANNOT_EXPAND_MESSAGE;
    public static final Status BUS_CONNECTION_REJECTED;
    public static final Status BUS_CONNECT_FAILED;
    public static final Status BUS_CORRUPT_KEYSTORE;
    public static final Status BUS_DESTINATION_NOT_AUTHENTICATED;
    public static final Status BUS_ELEMENT_NOT_FOUND;
    public static final Status BUS_EMPTY_MESSAGE;
    public static final Status BUS_ENDPOINT_CLOSING;
    public static final Status BUS_ENDPOINT_REDIRECTED;
    public static final Status BUS_ERRORS;
    public static final Status BUS_ERROR_NAME_MISSING;
    public static final Status BUS_ERROR_RESPONSE;
    public static final Status BUS_ESTABLISH_FAILED;
    public static final Status BUS_HANDLES_MISMATCH;
    public static final Status BUS_HANDLES_NOT_ENABLED;
    public static final Status BUS_HDR_EXPANSION_INVALID;
    public static final Status BUS_IFACE_ALREADY_EXISTS;
    public static final Status BUS_INCOMPATIBLE_DAEMON;
    public static final Status BUS_INTERFACE_ACTIVATED;
    public static final Status BUS_INTERFACE_MISMATCH;
    public static final Status BUS_INTERFACE_MISSING;
    public static final Status BUS_INTERFACE_NO_SUCH_MEMBER;
    public static final Status BUS_INVALID_AUTH_MECHANISM;
    public static final Status BUS_INVALID_HEADER_CHECKSUM;
    public static final Status BUS_INVALID_HEADER_SERIAL;
    public static final Status BUS_KEYBLOB_OP_INVALID;
    public static final Status BUS_KEYSTORE_NOT_LOADED;
    public static final Status BUS_KEYSTORE_VERSION_MISMATCH;
    public static final Status BUS_KEY_EXPIRED;
    public static final Status BUS_KEY_STORE_NOT_LOADED;
    public static final Status BUS_KEY_UNAVAILABLE;
    public static final Status BUS_LISTENER_ALREADY_SET;
    public static final Status BUS_MEMBER_ALREADY_EXISTS;
    public static final Status BUS_MEMBER_MISSING;
    public static final Status BUS_MEMBER_NO_SUCH_SIGNATURE;
    public static final Status BUS_MESSAGE_DECRYPTION_FAILED;
    public static final Status BUS_MESSAGE_NOT_ENCRYPTED;
    public static final Status BUS_METHOD_CALL_ABORTED;
    public static final Status BUS_MISSING_COMPRESSION_TOKEN;
    public static final Status BUS_NAME_TOO_LONG;
    public static final Status BUS_NOT_ALLOWED;
    public static final Status BUS_NOT_AUTHENTICATING;
    public static final Status BUS_NOT_AUTHORIZED;
    public static final Status BUS_NOT_A_COMPLETE_TYPE;
    public static final Status BUS_NOT_A_DICTIONARY;
    public static final Status BUS_NOT_COMPRESSED;
    public static final Status BUS_NOT_CONNECTED;
    public static final Status BUS_NOT_NUL_TERMINATED;
    public static final Status BUS_NOT_OWNER;
    public static final Status BUS_NO_AUTHENTICATION_MECHANISM;
    public static final Status BUS_NO_CALL_FOR_REPLY;
    public static final Status BUS_NO_ENDPOINT;
    public static final Status BUS_NO_LISTENER;
    public static final Status BUS_NO_PEER_GUID;
    public static final Status BUS_NO_ROUTE;
    public static final Status BUS_NO_SESSION;
    public static final Status BUS_NO_SUCH_ANNOTATION;
    public static final Status BUS_NO_SUCH_HANDLE;
    public static final Status BUS_NO_SUCH_INTERFACE;
    public static final Status BUS_NO_SUCH_MESSAGE;
    public static final Status BUS_NO_SUCH_OBJECT;
    public static final Status BUS_NO_SUCH_PROPERTY;
    public static final Status BUS_NO_SUCH_SERVICE;
    public static final Status BUS_NO_TRANSPORTS;
    public static final Status BUS_OBJECT_NOT_REGISTERED;
    public static final Status BUS_OBJECT_NO_SUCH_INTERFACE;
    public static final Status BUS_OBJECT_NO_SUCH_MEMBER;
    public static final Status BUS_OBJ_ALREADY_EXISTS;
    public static final Status BUS_OBJ_NOT_FOUND;
    public static final Status BUS_PATH_MISSING;
    public static final Status BUS_PEER_AUTH_VERSION_MISMATCH;
    public static final Status BUS_POLICY_VIOLATION;
    public static final Status BUS_PROPERTY_ACCESS_DENIED;
    public static final Status BUS_PROPERTY_ALREADY_EXISTS;
    public static final Status BUS_PROPERTY_VALUE_NOT_SET;
    public static final Status BUS_READ_ERROR;
    public static final Status BUS_REMOVED_BY_BINDER;
    public static final Status BUS_REPLY_IS_ERROR_MESSAGE;
    public static final Status BUS_REPLY_SERIAL_MISSING;
    public static final Status BUS_SECURITY_FATAL;
    public static final Status BUS_SECURITY_NOT_ENABLED;
    public static final Status BUS_SELF_CONNECT;
    public static final Status BUS_SET_PROPERTY_REJECTED;
    public static final Status BUS_SET_WRONG_SIGNATURE;
    public static final Status BUS_SIGNATURE_MISMATCH;
    public static final Status BUS_STOPPING;
    public static final Status BUS_TIME_TO_LIVE_EXPIRED;
    public static final Status BUS_TRANSPORT_NOT_AVAILABLE;
    public static final Status BUS_TRANSPORT_NOT_STARTED;
    public static final Status BUS_TRUNCATED;
    public static final Status BUS_UNEXPECTED_DISPOSITION;
    public static final Status BUS_UNEXPECTED_SIGNATURE;
    public static final Status BUS_UNKNOWN_INTERFACE;
    public static final Status BUS_UNKNOWN_PATH;
    public static final Status BUS_UNKNOWN_SERIAL;
    public static final Status BUS_UNMATCHED_REPLY_SERIAL;
    public static final Status BUS_WAIT_FAILED;
    public static final Status BUS_WRITE_ERROR;
    public static final Status BUS_WRITE_QUEUE_FULL;
    public static final Status CANCELLED;
    public static final Status COMMON_ERRORS;
    public static final Status CONN_REFUSED;
    public static final Status CORRUPT_KEYBLOB;
    public static final Status CRYPTO_ERROR;
    public static final Status CRYPTO_HASH_UNINITIALIZED;
    public static final Status CRYPTO_ILLEGAL_PARAMETERS;
    public static final Status CRYPTO_INSUFFICIENT_SECURITY;
    public static final Status CRYPTO_KEY_UNAVAILABLE;
    public static final Status CRYPTO_KEY_UNUSABLE;
    public static final Status CRYPTO_TRUNCATED;
    public static final Status DBUS_RELEASE_NAME_REPLY_NON_EXISTENT;
    public static final Status DBUS_RELEASE_NAME_REPLY_NOT_OWNER;
    public static final Status DBUS_RELEASE_NAME_REPLY_RELEASED;
    public static final Status DBUS_REQUEST_NAME_REPLY_ALREADY_OWNER;
    public static final Status DBUS_REQUEST_NAME_REPLY_EXISTS;
    public static final Status DBUS_REQUEST_NAME_REPLY_IN_QUEUE;
    public static final Status DBUS_REQUEST_NAME_REPLY_PRIMARY_OWNER;
    public static final Status DBUS_START_REPLY_ALREADY_RUNNING;
    public static final Status DEAD_THREAD;
    public static final Status EMPTY_KEY_BLOB;
    public static final Status END_OF_DATA;
    public static final Status EXTERNAL_THREAD;
    public static final Status FAIL;
    public static final Status ICE_ALLOCATE_REJECTED_NO_RESOURCES;
    public static final Status ICE_ALLOCATING_MEMORY;
    public static final Status ICE_ALLOCATION_MISMATCH;
    public static final Status ICE_ALLOCATION_QUOTA_REACHED;
    public static final Status ICE_CHECKS_INCOMPLETE;
    public static final Status ICE_INVALID_STATE;
    public static final Status ICE_STUN_ERROR;
    public static final Status ICE_UNKNOWN_COMPONENT_ID;
    public static final Status INIT_FAILED;
    public static final Status INVALID_ADDRESS;
    public static final Status INVALID_CONNECT_ARGS;
    public static final Status INVALID_DATA;
    public static final Status INVALID_GUID;
    public static final Status INVALID_HTTP_METHOD_USED_FOR_RENDEZVOUS_SERVER_INTERFACE_MESSAGE;
    public static final Status INVALID_KEY_ENCODING;
    public static final Status INVALID_ON_DEMAND_CONNECTION_MESSAGE_RESPONSE;
    public static final Status INVALID_PERSISTENT_CONNECTION_MESSAGE_RESPONSE;
    public static final Status INVALID_RENDEZVOUS_SERVER_INTERFACE_MESSAGE;
    public static final Status INVALID_STREAM;
    public static final Status IODISPATCH_STOPPING;
    public static final Status NONE;
    public static final Status NOT_CONNECTED_TO_RENDEZVOUS_SERVER;
    public static final Status NOT_IMPLEMENTED;
    public static final Status NO_SUCH_ALARM;
    public static final Status NO_SUCH_DEVICE;
    public static final Status OK;
    public static final Status OPEN_FAILED;
    public static final Status OS_ERROR;
    public static final Status OUT_OF_MEMORY;
    public static final Status P2P;
    public static final Status P2P_BUSY;
    public static final Status P2P_DISABLED;
    public static final Status P2P_FORBIDDEN;
    public static final Status P2P_NOT_CONNECTED;
    public static final Status P2P_NO_GO;
    public static final Status P2P_NO_STA;
    public static final Status P2P_TIMEOUT;
    public static final Status PACKET_BAD_CRC;
    public static final Status PACKET_BAD_FORMAT;
    public static final Status PACKET_BAD_PARAMETER;
    public static final Status PACKET_BUS_NO_SUCH_CHANNEL;
    public static final Status PACKET_CHANNEL_FAIL;
    public static final Status PACKET_CONNECT_TIMEOUT;
    public static final Status PACKET_TOO_LARGE;
    public static final Status PARSE_ERROR;
    public static final Status PROXIMITY_CONNECTION_ESTABLISH_FAIL;
    public static final Status PROXIMITY_NO_PEERS_FOUND;
    public static final Status READ_ERROR;
    public static final Status RENDEZVOUS_SERVER_DEACTIVATED_USER;
    public static final Status RENDEZVOUS_SERVER_ERR401_UNAUTHORIZED_REQUEST;
    public static final Status RENDEZVOUS_SERVER_ERR500_INTERNAL_ERROR;
    public static final Status RENDEZVOUS_SERVER_ERR503_STATUS_UNAVAILABLE;
    public static final Status RENDEZVOUS_SERVER_ROOT_CERTIFICATE_UNINITIALIZED;
    public static final Status RENDEZVOUS_SERVER_UNKNOWN_USER;
    public static final Status RENDEZVOUS_SERVER_UNRECOVERABLE_ERROR;
    public static final Status SLAP_CRC_ERROR;
    public static final Status SLAP_ERROR;
    public static final Status SLAP_HDR_CHECKSUM_ERROR;
    public static final Status SLAP_INVALID_PACKET_LEN;
    public static final Status SLAP_INVALID_PACKET_TYPE;
    public static final Status SLAP_LEN_MISMATCH;
    public static final Status SLAP_OTHER_END_CLOSED;
    public static final Status SLAP_PACKET_TYPE_MISMATCH;
    public static final Status SOCKET_BIND_ERROR;
    public static final Status SOCK_CLOSING;
    public static final Status SOCK_OTHER_END_CLOSED;
    public static final Status SSL_CONNECT;
    public static final Status SSL_ERRORS;
    public static final Status SSL_INIT;
    public static final Status SSL_VERIFY;
    public static final Status STOPPING_THREAD;
    public static final Status STUN_ATTR_SIZE_MISMATCH;
    public static final Status STUN_AUTH_CHALLENGE;
    public static final Status STUN_BAD_INDICATION;
    public static final Status STUN_DUPLICATE_ATTRIBUTE;
    public static final Status STUN_ERR400_BAD_REQUEST;
    public static final Status STUN_ERR401_UNAUTHORIZED_REQUEST;
    public static final Status STUN_FAILED_TO_SEND_MSG;
    public static final Status STUN_FRAMING_ERROR;
    public static final Status STUN_INVALID_ADDR_FAMILY;
    public static final Status STUN_INVALID_ATTR_TYPE;
    public static final Status STUN_INVALID_ERROR_CODE;
    public static final Status STUN_INVALID_FINGERPRINT;
    public static final Status STUN_INVALID_MESSAGE_INTEGRITY;
    public static final Status STUN_INVALID_MSG_TYPE;
    public static final Status STUN_RESPONSE_WITH_USERNAME;
    public static final Status STUN_SOCKET_NOT_OPEN;
    public static final Status STUN_SOCKET_OPEN;
    public static final Status STUN_TOO_MANY_ATTRIBUTES;
    public static final Status STUN_UNAUTHORIZED_INDICATION;
    public static final Status THREADPOOL_EXHAUSTED;
    public static final Status THREADPOOL_STOPPING;
    public static final Status THREAD_NO_WAIT;
    public static final Status THREAD_RUNNING;
    public static final Status THREAD_STOPPING;
    public static final Status TIMEOUT;
    public static final Status TIMER_EXITING;
    public static final Status TIMER_FALLBEHIND;
    public static final Status TIMER_FULL;
    public static final Status UNABLE_TO_CONNECT_TO_RENDEZVOUS_SERVER;
    public static final Status UNABLE_TO_SEND_MESSAGE_TO_RENDEZVOUS_SERVER;
    public static final Status UTF_CONVERSION_FAILED;
    public static final Status WARNING;
    public static final Status WOULDBLOCK;
    public static final Status WRITE_ERROR;
    public static final Status XML_MALFORMED;
    private int errorCode;

    private Status(String s, int i, int j)
    {
        super(s, i);
        errorCode = j;
    }

    private static Status create(int i)
    {
        Status astatus[] = values();
        int j = astatus.length;
        for (int k = 0; k < j; k++)
        {
            Status status = astatus[k];
            if (status.getErrorCode() == i)
                return status;
        }

        return NONE;
    }

    public static Status valueOf(String s)
    {
        return (Status)Enum.valueOf(org/alljoyn/bus/Status, s);
    }

    public static Status[] values()
    {
        return (Status[])$VALUES.clone();
    }

    public int getErrorCode()
    {
        return errorCode;
    }

    static 
    {
        OK = new Status("OK", 0, 0);
        FAIL = new Status("FAIL", 1, 1);
        UTF_CONVERSION_FAILED = new Status("UTF_CONVERSION_FAILED", 2, 2);
        BUFFER_TOO_SMALL = new Status("BUFFER_TOO_SMALL", 3, 3);
        OS_ERROR = new Status("OS_ERROR", 4, 4);
        OUT_OF_MEMORY = new Status("OUT_OF_MEMORY", 5, 5);
        SOCKET_BIND_ERROR = new Status("SOCKET_BIND_ERROR", 6, 6);
        INIT_FAILED = new Status("INIT_FAILED", 7, 7);
        WOULDBLOCK = new Status("WOULDBLOCK", 8, 8);
        NOT_IMPLEMENTED = new Status("NOT_IMPLEMENTED", 9, 9);
        TIMEOUT = new Status("TIMEOUT", 10, 10);
        SOCK_OTHER_END_CLOSED = new Status("SOCK_OTHER_END_CLOSED", 11, 11);
        BAD_ARG_1 = new Status("BAD_ARG_1", 12, 12);
        BAD_ARG_2 = new Status("BAD_ARG_2", 13, 13);
        BAD_ARG_3 = new Status("BAD_ARG_3", 14, 14);
        BAD_ARG_4 = new Status("BAD_ARG_4", 15, 15);
        BAD_ARG_5 = new Status("BAD_ARG_5", 16, 16);
        BAD_ARG_6 = new Status("BAD_ARG_6", 17, 17);
        BAD_ARG_7 = new Status("BAD_ARG_7", 18, 18);
        BAD_ARG_8 = new Status("BAD_ARG_8", 19, 19);
        INVALID_ADDRESS = new Status("INVALID_ADDRESS", 20, 20);
        INVALID_DATA = new Status("INVALID_DATA", 21, 21);
        READ_ERROR = new Status("READ_ERROR", 22, 22);
        WRITE_ERROR = new Status("WRITE_ERROR", 23, 23);
        OPEN_FAILED = new Status("OPEN_FAILED", 24, 24);
        PARSE_ERROR = new Status("PARSE_ERROR", 25, 25);
        END_OF_DATA = new Status("END_OF_DATA", 26, 26);
        CONN_REFUSED = new Status("CONN_REFUSED", 27, 27);
        BAD_ARG_COUNT = new Status("BAD_ARG_COUNT", 28, 28);
        WARNING = new Status("WARNING", 29, 29);
        COMMON_ERRORS = new Status("COMMON_ERRORS", 30, 4096);
        STOPPING_THREAD = new Status("STOPPING_THREAD", 31, 4097);
        ALERTED_THREAD = new Status("ALERTED_THREAD", 32, 4098);
        XML_MALFORMED = new Status("XML_MALFORMED", 33, 4099);
        AUTH_FAIL = new Status("AUTH_FAIL", 34, 4100);
        AUTH_USER_REJECT = new Status("AUTH_USER_REJECT", 35, 4101);
        NO_SUCH_ALARM = new Status("NO_SUCH_ALARM", 36, 4102);
        TIMER_FALLBEHIND = new Status("TIMER_FALLBEHIND", 37, 4103);
        SSL_ERRORS = new Status("SSL_ERRORS", 38, 4104);
        SSL_INIT = new Status("SSL_INIT", 39, 4105);
        SSL_CONNECT = new Status("SSL_CONNECT", 40, 4106);
        SSL_VERIFY = new Status("SSL_VERIFY", 41, 4107);
        EXTERNAL_THREAD = new Status("EXTERNAL_THREAD", 42, 4108);
        CRYPTO_ERROR = new Status("CRYPTO_ERROR", 43, 4109);
        CRYPTO_TRUNCATED = new Status("CRYPTO_TRUNCATED", 44, 4110);
        CRYPTO_KEY_UNAVAILABLE = new Status("CRYPTO_KEY_UNAVAILABLE", 45, 4111);
        BAD_HOSTNAME = new Status("BAD_HOSTNAME", 46, 4112);
        CRYPTO_KEY_UNUSABLE = new Status("CRYPTO_KEY_UNUSABLE", 47, 4113);
        EMPTY_KEY_BLOB = new Status("EMPTY_KEY_BLOB", 48, 4114);
        CORRUPT_KEYBLOB = new Status("CORRUPT_KEYBLOB", 49, 4115);
        INVALID_KEY_ENCODING = new Status("INVALID_KEY_ENCODING", 50, 4116);
        DEAD_THREAD = new Status("DEAD_THREAD", 51, 4117);
        THREAD_RUNNING = new Status("THREAD_RUNNING", 52, 4118);
        THREAD_STOPPING = new Status("THREAD_STOPPING", 53, 4119);
        BAD_STRING_ENCODING = new Status("BAD_STRING_ENCODING", 54, 4120);
        CRYPTO_INSUFFICIENT_SECURITY = new Status("CRYPTO_INSUFFICIENT_SECURITY", 55, 4121);
        CRYPTO_ILLEGAL_PARAMETERS = new Status("CRYPTO_ILLEGAL_PARAMETERS", 56, 4122);
        CRYPTO_HASH_UNINITIALIZED = new Status("CRYPTO_HASH_UNINITIALIZED", 57, 4123);
        THREAD_NO_WAIT = new Status("THREAD_NO_WAIT", 58, 4124);
        TIMER_EXITING = new Status("TIMER_EXITING", 59, 4125);
        INVALID_GUID = new Status("INVALID_GUID", 60, 4126);
        THREADPOOL_EXHAUSTED = new Status("THREADPOOL_EXHAUSTED", 61, 4127);
        THREADPOOL_STOPPING = new Status("THREADPOOL_STOPPING", 62, 4128);
        INVALID_STREAM = new Status("INVALID_STREAM", 63, 4129);
        TIMER_FULL = new Status("TIMER_FULL", 64, 4130);
        IODISPATCH_STOPPING = new Status("IODISPATCH_STOPPING", 65, 4131);
        SLAP_INVALID_PACKET_LEN = new Status("SLAP_INVALID_PACKET_LEN", 66, 4132);
        SLAP_HDR_CHECKSUM_ERROR = new Status("SLAP_HDR_CHECKSUM_ERROR", 67, 4133);
        SLAP_INVALID_PACKET_TYPE = new Status("SLAP_INVALID_PACKET_TYPE", 68, 4134);
        SLAP_LEN_MISMATCH = new Status("SLAP_LEN_MISMATCH", 69, 4135);
        SLAP_PACKET_TYPE_MISMATCH = new Status("SLAP_PACKET_TYPE_MISMATCH", 70, 4136);
        SLAP_CRC_ERROR = new Status("SLAP_CRC_ERROR", 71, 4137);
        SLAP_ERROR = new Status("SLAP_ERROR", 72, 4138);
        SLAP_OTHER_END_CLOSED = new Status("SLAP_OTHER_END_CLOSED", 73, 4139);
        NONE = new Status("NONE", 74, 65535);
        BUS_ERRORS = new Status("BUS_ERRORS", 75, 36864);
        BUS_READ_ERROR = new Status("BUS_READ_ERROR", 76, 36865);
        BUS_WRITE_ERROR = new Status("BUS_WRITE_ERROR", 77, 36866);
        BUS_BAD_VALUE_TYPE = new Status("BUS_BAD_VALUE_TYPE", 78, 36867);
        BUS_BAD_HEADER_FIELD = new Status("BUS_BAD_HEADER_FIELD", 79, 36868);
        BUS_BAD_SIGNATURE = new Status("BUS_BAD_SIGNATURE", 80, 36869);
        BUS_BAD_OBJ_PATH = new Status("BUS_BAD_OBJ_PATH", 81, 36870);
        BUS_BAD_MEMBER_NAME = new Status("BUS_BAD_MEMBER_NAME", 82, 36871);
        BUS_BAD_INTERFACE_NAME = new Status("BUS_BAD_INTERFACE_NAME", 83, 36872);
        BUS_BAD_ERROR_NAME = new Status("BUS_BAD_ERROR_NAME", 84, 36873);
        BUS_BAD_BUS_NAME = new Status("BUS_BAD_BUS_NAME", 85, 36874);
        BUS_NAME_TOO_LONG = new Status("BUS_NAME_TOO_LONG", 86, 36875);
        BUS_BAD_LENGTH = new Status("BUS_BAD_LENGTH", 87, 36876);
        BUS_BAD_VALUE = new Status("BUS_BAD_VALUE", 88, 36877);
        BUS_BAD_HDR_FLAGS = new Status("BUS_BAD_HDR_FLAGS", 89, 36878);
        BUS_BAD_BODY_LEN = new Status("BUS_BAD_BODY_LEN", 90, 36879);
        BUS_BAD_HEADER_LEN = new Status("BUS_BAD_HEADER_LEN", 91, 36880);
        BUS_UNKNOWN_SERIAL = new Status("BUS_UNKNOWN_SERIAL", 92, 36881);
        BUS_UNKNOWN_PATH = new Status("BUS_UNKNOWN_PATH", 93, 36882);
        BUS_UNKNOWN_INTERFACE = new Status("BUS_UNKNOWN_INTERFACE", 94, 36883);
        BUS_ESTABLISH_FAILED = new Status("BUS_ESTABLISH_FAILED", 95, 36884);
        BUS_UNEXPECTED_SIGNATURE = new Status("BUS_UNEXPECTED_SIGNATURE", 96, 36885);
        BUS_INTERFACE_MISSING = new Status("BUS_INTERFACE_MISSING", 97, 36886);
        BUS_PATH_MISSING = new Status("BUS_PATH_MISSING", 98, 36887);
        BUS_MEMBER_MISSING = new Status("BUS_MEMBER_MISSING", 99, 36888);
        BUS_REPLY_SERIAL_MISSING = new Status("BUS_REPLY_SERIAL_MISSING", 100, 36889);
        BUS_ERROR_NAME_MISSING = new Status("BUS_ERROR_NAME_MISSING", 101, 36890);
        BUS_INTERFACE_NO_SUCH_MEMBER = new Status("BUS_INTERFACE_NO_SUCH_MEMBER", 102, 36891);
        BUS_NO_SUCH_OBJECT = new Status("BUS_NO_SUCH_OBJECT", 103, 36892);
        BUS_OBJECT_NO_SUCH_MEMBER = new Status("BUS_OBJECT_NO_SUCH_MEMBER", 104, 36893);
        BUS_OBJECT_NO_SUCH_INTERFACE = new Status("BUS_OBJECT_NO_SUCH_INTERFACE", 105, 36894);
        BUS_NO_SUCH_INTERFACE = new Status("BUS_NO_SUCH_INTERFACE", 106, 36895);
        BUS_MEMBER_NO_SUCH_SIGNATURE = new Status("BUS_MEMBER_NO_SUCH_SIGNATURE", 107, 36896);
        BUS_NOT_NUL_TERMINATED = new Status("BUS_NOT_NUL_TERMINATED", 108, 36897);
        BUS_NO_SUCH_PROPERTY = new Status("BUS_NO_SUCH_PROPERTY", 109, 36898);
        BUS_SET_WRONG_SIGNATURE = new Status("BUS_SET_WRONG_SIGNATURE", 110, 36899);
        BUS_PROPERTY_VALUE_NOT_SET = new Status("BUS_PROPERTY_VALUE_NOT_SET", 111, 36900);
        BUS_PROPERTY_ACCESS_DENIED = new Status("BUS_PROPERTY_ACCESS_DENIED", 112, 36901);
        BUS_NO_TRANSPORTS = new Status("BUS_NO_TRANSPORTS", 113, 36902);
        BUS_BAD_TRANSPORT_ARGS = new Status("BUS_BAD_TRANSPORT_ARGS", 114, 36903);
        BUS_NO_ROUTE = new Status("BUS_NO_ROUTE", 115, 36904);
        BUS_NO_ENDPOINT = new Status("BUS_NO_ENDPOINT", 116, 36905);
        BUS_BAD_SEND_PARAMETER = new Status("BUS_BAD_SEND_PARAMETER", 117, 36906);
        BUS_UNMATCHED_REPLY_SERIAL = new Status("BUS_UNMATCHED_REPLY_SERIAL", 118, 36907);
        BUS_BAD_SENDER_ID = new Status("BUS_BAD_SENDER_ID", 119, 36908);
        BUS_TRANSPORT_NOT_STARTED = new Status("BUS_TRANSPORT_NOT_STARTED", 120, 36909);
        BUS_EMPTY_MESSAGE = new Status("BUS_EMPTY_MESSAGE", 121, 36910);
        BUS_NOT_OWNER = new Status("BUS_NOT_OWNER", 122, 36911);
        BUS_SET_PROPERTY_REJECTED = new Status("BUS_SET_PROPERTY_REJECTED", 123, 36912);
        BUS_CONNECT_FAILED = new Status("BUS_CONNECT_FAILED", 124, 36913);
        BUS_REPLY_IS_ERROR_MESSAGE = new Status("BUS_REPLY_IS_ERROR_MESSAGE", 125, 36914);
        BUS_NOT_AUTHENTICATING = new Status("BUS_NOT_AUTHENTICATING", 126, 36915);
        BUS_NO_LISTENER = new Status("BUS_NO_LISTENER", 127, 36916);
        BUS_BT_TRANSPORT_ERROR = new Status("BUS_BT_TRANSPORT_ERROR", 128, 36917);
        BUS_NOT_ALLOWED = new Status("BUS_NOT_ALLOWED", 129, 36918);
        BUS_WRITE_QUEUE_FULL = new Status("BUS_WRITE_QUEUE_FULL", 130, 36919);
        BUS_ENDPOINT_CLOSING = new Status("BUS_ENDPOINT_CLOSING", 131, 36920);
        BUS_INTERFACE_MISMATCH = new Status("BUS_INTERFACE_MISMATCH", 132, 36921);
        BUS_MEMBER_ALREADY_EXISTS = new Status("BUS_MEMBER_ALREADY_EXISTS", 133, 36922);
        BUS_PROPERTY_ALREADY_EXISTS = new Status("BUS_PROPERTY_ALREADY_EXISTS", 134, 36923);
        BUS_IFACE_ALREADY_EXISTS = new Status("BUS_IFACE_ALREADY_EXISTS", 135, 36924);
        BUS_ERROR_RESPONSE = new Status("BUS_ERROR_RESPONSE", 136, 36925);
        BUS_BAD_XML = new Status("BUS_BAD_XML", 137, 36926);
        BUS_BAD_CHILD_PATH = new Status("BUS_BAD_CHILD_PATH", 138, 36927);
        BUS_OBJ_ALREADY_EXISTS = new Status("BUS_OBJ_ALREADY_EXISTS", 139, 36928);
        BUS_OBJ_NOT_FOUND = new Status("BUS_OBJ_NOT_FOUND", 140, 36929);
        BUS_CANNOT_EXPAND_MESSAGE = new Status("BUS_CANNOT_EXPAND_MESSAGE", 141, 36930);
        BUS_NOT_COMPRESSED = new Status("BUS_NOT_COMPRESSED", 142, 36931);
        BUS_ALREADY_CONNECTED = new Status("BUS_ALREADY_CONNECTED", 143, 36932);
        BUS_NOT_CONNECTED = new Status("BUS_NOT_CONNECTED", 144, 36933);
        BUS_ALREADY_LISTENING = new Status("BUS_ALREADY_LISTENING", 145, 36934);
        BUS_KEY_UNAVAILABLE = new Status("BUS_KEY_UNAVAILABLE", 146, 36935);
        BUS_TRUNCATED = new Status("BUS_TRUNCATED", 147, 36936);
        BUS_KEY_STORE_NOT_LOADED = new Status("BUS_KEY_STORE_NOT_LOADED", 148, 36937);
        BUS_NO_AUTHENTICATION_MECHANISM = new Status("BUS_NO_AUTHENTICATION_MECHANISM", 149, 36938);
        BUS_BUS_ALREADY_STARTED = new Status("BUS_BUS_ALREADY_STARTED", 150, 36939);
        BUS_BUS_NOT_STARTED = new Status("BUS_BUS_NOT_STARTED", 151, 36940);
        BUS_KEYBLOB_OP_INVALID = new Status("BUS_KEYBLOB_OP_INVALID", 152, 36941);
        BUS_INVALID_HEADER_CHECKSUM = new Status("BUS_INVALID_HEADER_CHECKSUM", 153, 36942);
        BUS_MESSAGE_NOT_ENCRYPTED = new Status("BUS_MESSAGE_NOT_ENCRYPTED", 154, 36943);
        BUS_INVALID_HEADER_SERIAL = new Status("BUS_INVALID_HEADER_SERIAL", 155, 36944);
        BUS_TIME_TO_LIVE_EXPIRED = new Status("BUS_TIME_TO_LIVE_EXPIRED", 156, 36945);
        BUS_HDR_EXPANSION_INVALID = new Status("BUS_HDR_EXPANSION_INVALID", 157, 36946);
        BUS_MISSING_COMPRESSION_TOKEN = new Status("BUS_MISSING_COMPRESSION_TOKEN", 158, 36947);
        BUS_NO_PEER_GUID = new Status("BUS_NO_PEER_GUID", 159, 36948);
        BUS_MESSAGE_DECRYPTION_FAILED = new Status("BUS_MESSAGE_DECRYPTION_FAILED", 160, 36949);
        BUS_SECURITY_FATAL = new Status("BUS_SECURITY_FATAL", 161, 36950);
        BUS_KEY_EXPIRED = new Status("BUS_KEY_EXPIRED", 162, 36951);
        BUS_CORRUPT_KEYSTORE = new Status("BUS_CORRUPT_KEYSTORE", 163, 36952);
        BUS_NO_CALL_FOR_REPLY = new Status("BUS_NO_CALL_FOR_REPLY", 164, 36953);
        BUS_NOT_A_COMPLETE_TYPE = new Status("BUS_NOT_A_COMPLETE_TYPE", 165, 36954);
        BUS_POLICY_VIOLATION = new Status("BUS_POLICY_VIOLATION", 166, 36955);
        BUS_NO_SUCH_SERVICE = new Status("BUS_NO_SUCH_SERVICE", 167, 36956);
        BUS_TRANSPORT_NOT_AVAILABLE = new Status("BUS_TRANSPORT_NOT_AVAILABLE", 168, 36957);
        BUS_INVALID_AUTH_MECHANISM = new Status("BUS_INVALID_AUTH_MECHANISM", 169, 36958);
        BUS_KEYSTORE_VERSION_MISMATCH = new Status("BUS_KEYSTORE_VERSION_MISMATCH", 170, 36959);
        BUS_BLOCKING_CALL_NOT_ALLOWED = new Status("BUS_BLOCKING_CALL_NOT_ALLOWED", 171, 36960);
        BUS_SIGNATURE_MISMATCH = new Status("BUS_SIGNATURE_MISMATCH", 172, 36961);
        BUS_STOPPING = new Status("BUS_STOPPING", 173, 36962);
        BUS_METHOD_CALL_ABORTED = new Status("BUS_METHOD_CALL_ABORTED", 174, 36963);
        BUS_CANNOT_ADD_INTERFACE = new Status("BUS_CANNOT_ADD_INTERFACE", 175, 36964);
        BUS_CANNOT_ADD_HANDLER = new Status("BUS_CANNOT_ADD_HANDLER", 176, 36965);
        BUS_KEYSTORE_NOT_LOADED = new Status("BUS_KEYSTORE_NOT_LOADED", 177, 36966);
        BUS_NO_SUCH_HANDLE = new Status("BUS_NO_SUCH_HANDLE", 178, 36971);
        BUS_HANDLES_NOT_ENABLED = new Status("BUS_HANDLES_NOT_ENABLED", 179, 36972);
        BUS_HANDLES_MISMATCH = new Status("BUS_HANDLES_MISMATCH", 180, 36973);
        BT_MAX_CONNECTIONS_USED = new Status("BT_MAX_CONNECTIONS_USED", 181, 36974);
        BUS_NO_SESSION = new Status("BUS_NO_SESSION", 182, 36975);
        BUS_ELEMENT_NOT_FOUND = new Status("BUS_ELEMENT_NOT_FOUND", 183, 36976);
        BUS_NOT_A_DICTIONARY = new Status("BUS_NOT_A_DICTIONARY", 184, 36977);
        BUS_WAIT_FAILED = new Status("BUS_WAIT_FAILED", 185, 36978);
        BUS_BAD_SESSION_OPTS = new Status("BUS_BAD_SESSION_OPTS", 186, 36980);
        BUS_CONNECTION_REJECTED = new Status("BUS_CONNECTION_REJECTED", 187, 36981);
        DBUS_REQUEST_NAME_REPLY_PRIMARY_OWNER = new Status("DBUS_REQUEST_NAME_REPLY_PRIMARY_OWNER", 188, 36982);
        DBUS_REQUEST_NAME_REPLY_IN_QUEUE = new Status("DBUS_REQUEST_NAME_REPLY_IN_QUEUE", 189, 36983);
        DBUS_REQUEST_NAME_REPLY_EXISTS = new Status("DBUS_REQUEST_NAME_REPLY_EXISTS", 190, 36984);
        DBUS_REQUEST_NAME_REPLY_ALREADY_OWNER = new Status("DBUS_REQUEST_NAME_REPLY_ALREADY_OWNER", 191, 36985);
        DBUS_RELEASE_NAME_REPLY_RELEASED = new Status("DBUS_RELEASE_NAME_REPLY_RELEASED", 192, 36986);
        DBUS_RELEASE_NAME_REPLY_NON_EXISTENT = new Status("DBUS_RELEASE_NAME_REPLY_NON_EXISTENT", 193, 36987);
        DBUS_RELEASE_NAME_REPLY_NOT_OWNER = new Status("DBUS_RELEASE_NAME_REPLY_NOT_OWNER", 194, 36988);
        DBUS_START_REPLY_ALREADY_RUNNING = new Status("DBUS_START_REPLY_ALREADY_RUNNING", 195, 36990);
        ALLJOYN_BINDSESSIONPORT_REPLY_ALREADY_EXISTS = new Status("ALLJOYN_BINDSESSIONPORT_REPLY_ALREADY_EXISTS", 196, 36992);
        ALLJOYN_BINDSESSIONPORT_REPLY_FAILED = new Status("ALLJOYN_BINDSESSIONPORT_REPLY_FAILED", 197, 36993);
        ALLJOYN_JOINSESSION_REPLY_NO_SESSION = new Status("ALLJOYN_JOINSESSION_REPLY_NO_SESSION", 198, 36995);
        ALLJOYN_JOINSESSION_REPLY_UNREACHABLE = new Status("ALLJOYN_JOINSESSION_REPLY_UNREACHABLE", 199, 36996);
        ALLJOYN_JOINSESSION_REPLY_CONNECT_FAILED = new Status("ALLJOYN_JOINSESSION_REPLY_CONNECT_FAILED", 200, 36997);
        ALLJOYN_JOINSESSION_REPLY_REJECTED = new Status("ALLJOYN_JOINSESSION_REPLY_REJECTED", 201, 36998);
        ALLJOYN_JOINSESSION_REPLY_BAD_SESSION_OPTS = new Status("ALLJOYN_JOINSESSION_REPLY_BAD_SESSION_OPTS", 202, 36999);
        ALLJOYN_JOINSESSION_REPLY_FAILED = new Status("ALLJOYN_JOINSESSION_REPLY_FAILED", 203, 37000);
        ALLJOYN_LEAVESESSION_REPLY_NO_SESSION = new Status("ALLJOYN_LEAVESESSION_REPLY_NO_SESSION", 204, 37002);
        ALLJOYN_LEAVESESSION_REPLY_FAILED = new Status("ALLJOYN_LEAVESESSION_REPLY_FAILED", 205, 37003);
        ALLJOYN_ADVERTISENAME_REPLY_ALREADY_ADVERTISING = new Status("ALLJOYN_ADVERTISENAME_REPLY_ALREADY_ADVERTISING", 206, 37005);
        ALLJOYN_ADVERTISENAME_REPLY_FAILED = new Status("ALLJOYN_ADVERTISENAME_REPLY_FAILED", 207, 37006);
        ALLJOYN_CANCELADVERTISENAME_REPLY_FAILED = new Status("ALLJOYN_CANCELADVERTISENAME_REPLY_FAILED", 208, 37008);
        ALLJOYN_FINDADVERTISEDNAME_REPLY_ALREADY_DISCOVERING = new Status("ALLJOYN_FINDADVERTISEDNAME_REPLY_ALREADY_DISCOVERING", 209, 37010);
        ALLJOYN_FINDADVERTISEDNAME_REPLY_FAILED = new Status("ALLJOYN_FINDADVERTISEDNAME_REPLY_FAILED", 210, 37011);
        ALLJOYN_CANCELFINDADVERTISEDNAME_REPLY_FAILED = new Status("ALLJOYN_CANCELFINDADVERTISEDNAME_REPLY_FAILED", 211, 37013);
        BUS_UNEXPECTED_DISPOSITION = new Status("BUS_UNEXPECTED_DISPOSITION", 212, 37014);
        BUS_INTERFACE_ACTIVATED = new Status("BUS_INTERFACE_ACTIVATED", 213, 37015);
        ALLJOYN_UNBINDSESSIONPORT_REPLY_BAD_PORT = new Status("ALLJOYN_UNBINDSESSIONPORT_REPLY_BAD_PORT", 214, 37016);
        ALLJOYN_UNBINDSESSIONPORT_REPLY_FAILED = new Status("ALLJOYN_UNBINDSESSIONPORT_REPLY_FAILED", 215, 37017);
        ALLJOYN_BINDSESSIONPORT_REPLY_INVALID_OPTS = new Status("ALLJOYN_BINDSESSIONPORT_REPLY_INVALID_OPTS", 216, 37018);
        ALLJOYN_JOINSESSION_REPLY_ALREADY_JOINED = new Status("ALLJOYN_JOINSESSION_REPLY_ALREADY_JOINED", 217, 37019);
        BUS_SELF_CONNECT = new Status("BUS_SELF_CONNECT", 218, 37020);
        BUS_SECURITY_NOT_ENABLED = new Status("BUS_SECURITY_NOT_ENABLED", 219, 37021);
        BUS_LISTENER_ALREADY_SET = new Status("BUS_LISTENER_ALREADY_SET", 220, 37022);
        BUS_PEER_AUTH_VERSION_MISMATCH = new Status("BUS_PEER_AUTH_VERSION_MISMATCH", 221, 37023);
        ALLJOYN_SETLINKTIMEOUT_REPLY_NOT_SUPPORTED = new Status("ALLJOYN_SETLINKTIMEOUT_REPLY_NOT_SUPPORTED", 222, 37024);
        ALLJOYN_SETLINKTIMEOUT_REPLY_NO_DEST_SUPPORT = new Status("ALLJOYN_SETLINKTIMEOUT_REPLY_NO_DEST_SUPPORT", 223, 37025);
        ALLJOYN_SETLINKTIMEOUT_REPLY_FAILED = new Status("ALLJOYN_SETLINKTIMEOUT_REPLY_FAILED", 224, 37026);
        ALLJOYN_ACCESS_PERMISSION_WARNING = new Status("ALLJOYN_ACCESS_PERMISSION_WARNING", 225, 37027);
        ALLJOYN_ACCESS_PERMISSION_ERROR = new Status("ALLJOYN_ACCESS_PERMISSION_ERROR", 226, 37028);
        BUS_DESTINATION_NOT_AUTHENTICATED = new Status("BUS_DESTINATION_NOT_AUTHENTICATED", 227, 37029);
        BUS_ENDPOINT_REDIRECTED = new Status("BUS_ENDPOINT_REDIRECTED", 228, 37030);
        BUS_AUTHENTICATION_PENDING = new Status("BUS_AUTHENTICATION_PENDING", 229, 37031);
        BUS_NOT_AUTHORIZED = new Status("BUS_NOT_AUTHORIZED", 230, 37032);
        PACKET_BUS_NO_SUCH_CHANNEL = new Status("PACKET_BUS_NO_SUCH_CHANNEL", 231, 37033);
        PACKET_BAD_FORMAT = new Status("PACKET_BAD_FORMAT", 232, 37034);
        PACKET_CONNECT_TIMEOUT = new Status("PACKET_CONNECT_TIMEOUT", 233, 37035);
        PACKET_CHANNEL_FAIL = new Status("PACKET_CHANNEL_FAIL", 234, 37036);
        PACKET_TOO_LARGE = new Status("PACKET_TOO_LARGE", 235, 37037);
        PACKET_BAD_PARAMETER = new Status("PACKET_BAD_PARAMETER", 236, 37038);
        PACKET_BAD_CRC = new Status("PACKET_BAD_CRC", 237, 37039);
        STUN_ATTR_SIZE_MISMATCH = new Status("STUN_ATTR_SIZE_MISMATCH", 238, 37040);
        STUN_AUTH_CHALLENGE = new Status("STUN_AUTH_CHALLENGE", 239, 37041);
        STUN_SOCKET_NOT_OPEN = new Status("STUN_SOCKET_NOT_OPEN", 240, 37042);
        STUN_SOCKET_OPEN = new Status("STUN_SOCKET_OPEN", 241, 37043);
        STUN_FAILED_TO_SEND_MSG = new Status("STUN_FAILED_TO_SEND_MSG", 242, 37044);
        STUN_FRAMING_ERROR = new Status("STUN_FRAMING_ERROR", 243, 37045);
        STUN_INVALID_ERROR_CODE = new Status("STUN_INVALID_ERROR_CODE", 244, 37046);
        STUN_INVALID_FINGERPRINT = new Status("STUN_INVALID_FINGERPRINT", 245, 37047);
        STUN_INVALID_ADDR_FAMILY = new Status("STUN_INVALID_ADDR_FAMILY", 246, 37048);
        STUN_INVALID_MESSAGE_INTEGRITY = new Status("STUN_INVALID_MESSAGE_INTEGRITY", 247, 37049);
        STUN_INVALID_MSG_TYPE = new Status("STUN_INVALID_MSG_TYPE", 248, 37050);
        STUN_INVALID_ATTR_TYPE = new Status("STUN_INVALID_ATTR_TYPE", 249, 37051);
        STUN_RESPONSE_WITH_USERNAME = new Status("STUN_RESPONSE_WITH_USERNAME", 250, 37052);
        STUN_ERR400_BAD_REQUEST = new Status("STUN_ERR400_BAD_REQUEST", 251, 37053);
        STUN_BAD_INDICATION = new Status("STUN_BAD_INDICATION", 252, 37054);
        STUN_ERR401_UNAUTHORIZED_REQUEST = new Status("STUN_ERR401_UNAUTHORIZED_REQUEST", 253, 37055);
        STUN_TOO_MANY_ATTRIBUTES = new Status("STUN_TOO_MANY_ATTRIBUTES", 254, 37056);
        STUN_DUPLICATE_ATTRIBUTE = new Status("STUN_DUPLICATE_ATTRIBUTE", 255, 37057);
        STUN_UNAUTHORIZED_INDICATION = new Status("STUN_UNAUTHORIZED_INDICATION", 256, 37058);
        ICE_ALLOCATING_MEMORY = new Status("ICE_ALLOCATING_MEMORY", 257, 37059);
        ICE_CHECKS_INCOMPLETE = new Status("ICE_CHECKS_INCOMPLETE", 258, 37060);
        ICE_ALLOCATE_REJECTED_NO_RESOURCES = new Status("ICE_ALLOCATE_REJECTED_NO_RESOURCES", 259, 37061);
        ICE_ALLOCATION_QUOTA_REACHED = new Status("ICE_ALLOCATION_QUOTA_REACHED", 260, 37062);
        ICE_ALLOCATION_MISMATCH = new Status("ICE_ALLOCATION_MISMATCH", 261, 37063);
        ICE_STUN_ERROR = new Status("ICE_STUN_ERROR", 262, 37064);
        ICE_INVALID_STATE = new Status("ICE_INVALID_STATE", 263, 37065);
        ICE_UNKNOWN_COMPONENT_ID = new Status("ICE_UNKNOWN_COMPONENT_ID", 264, 37066);
        RENDEZVOUS_SERVER_DEACTIVATED_USER = new Status("RENDEZVOUS_SERVER_DEACTIVATED_USER", 265, 37067);
        RENDEZVOUS_SERVER_UNKNOWN_USER = new Status("RENDEZVOUS_SERVER_UNKNOWN_USER", 266, 37068);
        UNABLE_TO_CONNECT_TO_RENDEZVOUS_SERVER = new Status("UNABLE_TO_CONNECT_TO_RENDEZVOUS_SERVER", 267, 37069);
        NOT_CONNECTED_TO_RENDEZVOUS_SERVER = new Status("NOT_CONNECTED_TO_RENDEZVOUS_SERVER", 268, 37070);
        UNABLE_TO_SEND_MESSAGE_TO_RENDEZVOUS_SERVER = new Status("UNABLE_TO_SEND_MESSAGE_TO_RENDEZVOUS_SERVER", 269, 37071);
        INVALID_RENDEZVOUS_SERVER_INTERFACE_MESSAGE = new Status("INVALID_RENDEZVOUS_SERVER_INTERFACE_MESSAGE", 270, 37072);
        INVALID_PERSISTENT_CONNECTION_MESSAGE_RESPONSE = new Status("INVALID_PERSISTENT_CONNECTION_MESSAGE_RESPONSE", 271, 37073);
        INVALID_ON_DEMAND_CONNECTION_MESSAGE_RESPONSE = new Status("INVALID_ON_DEMAND_CONNECTION_MESSAGE_RESPONSE", 272, 37074);
        INVALID_HTTP_METHOD_USED_FOR_RENDEZVOUS_SERVER_INTERFACE_MESSAGE = new Status("INVALID_HTTP_METHOD_USED_FOR_RENDEZVOUS_SERVER_INTERFACE_MESSAGE", 273, 37075);
        RENDEZVOUS_SERVER_ERR500_INTERNAL_ERROR = new Status("RENDEZVOUS_SERVER_ERR500_INTERNAL_ERROR", 274, 37076);
        RENDEZVOUS_SERVER_ERR503_STATUS_UNAVAILABLE = new Status("RENDEZVOUS_SERVER_ERR503_STATUS_UNAVAILABLE", 275, 37077);
        RENDEZVOUS_SERVER_ERR401_UNAUTHORIZED_REQUEST = new Status("RENDEZVOUS_SERVER_ERR401_UNAUTHORIZED_REQUEST", 276, 37078);
        RENDEZVOUS_SERVER_UNRECOVERABLE_ERROR = new Status("RENDEZVOUS_SERVER_UNRECOVERABLE_ERROR", 277, 37079);
        RENDEZVOUS_SERVER_ROOT_CERTIFICATE_UNINITIALIZED = new Status("RENDEZVOUS_SERVER_ROOT_CERTIFICATE_UNINITIALIZED", 278, 37080);
        BUS_NO_SUCH_ANNOTATION = new Status("BUS_NO_SUCH_ANNOTATION", 279, 37081);
        BUS_ANNOTATION_ALREADY_EXISTS = new Status("BUS_ANNOTATION_ALREADY_EXISTS", 280, 37082);
        SOCK_CLOSING = new Status("SOCK_CLOSING", 281, 37083);
        NO_SUCH_DEVICE = new Status("NO_SUCH_DEVICE", 282, 37084);
        P2P = new Status("P2P", 283, 37085);
        P2P_TIMEOUT = new Status("P2P_TIMEOUT", 284, 37086);
        P2P_NOT_CONNECTED = new Status("P2P_NOT_CONNECTED", 285, 37087);
        BAD_TRANSPORT_MASK = new Status("BAD_TRANSPORT_MASK", 286, 37088);
        PROXIMITY_CONNECTION_ESTABLISH_FAIL = new Status("PROXIMITY_CONNECTION_ESTABLISH_FAIL", 287, 37089);
        PROXIMITY_NO_PEERS_FOUND = new Status("PROXIMITY_NO_PEERS_FOUND", 288, 37090);
        BUS_OBJECT_NOT_REGISTERED = new Status("BUS_OBJECT_NOT_REGISTERED", 289, 37091);
        P2P_DISABLED = new Status("P2P_DISABLED", 290, 37092);
        P2P_BUSY = new Status("P2P_BUSY", 291, 37093);
        BUS_INCOMPATIBLE_DAEMON = new Status("BUS_INCOMPATIBLE_DAEMON", 292, 37094);
        P2P_NO_GO = new Status("P2P_NO_GO", 293, 37095);
        P2P_NO_STA = new Status("P2P_NO_STA", 294, 37096);
        P2P_FORBIDDEN = new Status("P2P_FORBIDDEN", 295, 37097);
        ALLJOYN_ONAPPSUSPEND_REPLY_FAILED = new Status("ALLJOYN_ONAPPSUSPEND_REPLY_FAILED", 296, 37098);
        ALLJOYN_ONAPPSUSPEND_REPLY_UNSUPPORTED = new Status("ALLJOYN_ONAPPSUSPEND_REPLY_UNSUPPORTED", 297, 37099);
        ALLJOYN_ONAPPRESUME_REPLY_FAILED = new Status("ALLJOYN_ONAPPRESUME_REPLY_FAILED", 298, 37100);
        ALLJOYN_ONAPPRESUME_REPLY_UNSUPPORTED = new Status("ALLJOYN_ONAPPRESUME_REPLY_UNSUPPORTED", 299, 37101);
        BUS_NO_SUCH_MESSAGE = new Status("BUS_NO_SUCH_MESSAGE", 300, 37102);
        ALLJOYN_REMOVESESSIONMEMBER_REPLY_NO_SESSION = new Status("ALLJOYN_REMOVESESSIONMEMBER_REPLY_NO_SESSION", 301, 37103);
        ALLJOYN_REMOVESESSIONMEMBER_NOT_BINDER = new Status("ALLJOYN_REMOVESESSIONMEMBER_NOT_BINDER", 302, 37104);
        ALLJOYN_REMOVESESSIONMEMBER_NOT_MULTIPOINT = new Status("ALLJOYN_REMOVESESSIONMEMBER_NOT_MULTIPOINT", 303, 37105);
        ALLJOYN_REMOVESESSIONMEMBER_NOT_FOUND = new Status("ALLJOYN_REMOVESESSIONMEMBER_NOT_FOUND", 304, 37106);
        ALLJOYN_REMOVESESSIONMEMBER_INCOMPATIBLE_REMOTE_DAEMON = new Status("ALLJOYN_REMOVESESSIONMEMBER_INCOMPATIBLE_REMOTE_DAEMON", 305, 37107);
        ALLJOYN_REMOVESESSIONMEMBER_REPLY_FAILED = new Status("ALLJOYN_REMOVESESSIONMEMBER_REPLY_FAILED", 306, 37108);
        BUS_REMOVED_BY_BINDER = new Status("BUS_REMOVED_BY_BINDER", 307, 37109);
        BAD_ANNOTATION = new Status("BAD_ANNOTATION", 308, 40960);
        INVALID_CONNECT_ARGS = new Status("INVALID_CONNECT_ARGS", 309, 40961);
        ALREADY_FINDING = new Status("ALREADY_FINDING", 310, 40962);
        CANCELLED = new Status("CANCELLED", 311, 40963);
        ALREADY_REGISTERED = new Status("ALREADY_REGISTERED", 312, 40964);
        Status astatus[] = new Status[313];
        astatus[0] = OK;
        astatus[1] = FAIL;
        astatus[2] = UTF_CONVERSION_FAILED;
        astatus[3] = BUFFER_TOO_SMALL;
        astatus[4] = OS_ERROR;
        astatus[5] = OUT_OF_MEMORY;
        astatus[6] = SOCKET_BIND_ERROR;
        astatus[7] = INIT_FAILED;
        astatus[8] = WOULDBLOCK;
        astatus[9] = NOT_IMPLEMENTED;
        astatus[10] = TIMEOUT;
        astatus[11] = SOCK_OTHER_END_CLOSED;
        astatus[12] = BAD_ARG_1;
        astatus[13] = BAD_ARG_2;
        astatus[14] = BAD_ARG_3;
        astatus[15] = BAD_ARG_4;
        astatus[16] = BAD_ARG_5;
        astatus[17] = BAD_ARG_6;
        astatus[18] = BAD_ARG_7;
        astatus[19] = BAD_ARG_8;
        astatus[20] = INVALID_ADDRESS;
        astatus[21] = INVALID_DATA;
        astatus[22] = READ_ERROR;
        astatus[23] = WRITE_ERROR;
        astatus[24] = OPEN_FAILED;
        astatus[25] = PARSE_ERROR;
        astatus[26] = END_OF_DATA;
        astatus[27] = CONN_REFUSED;
        astatus[28] = BAD_ARG_COUNT;
        astatus[29] = WARNING;
        astatus[30] = COMMON_ERRORS;
        astatus[31] = STOPPING_THREAD;
        astatus[32] = ALERTED_THREAD;
        astatus[33] = XML_MALFORMED;
        astatus[34] = AUTH_FAIL;
        astatus[35] = AUTH_USER_REJECT;
        astatus[36] = NO_SUCH_ALARM;
        astatus[37] = TIMER_FALLBEHIND;
        astatus[38] = SSL_ERRORS;
        astatus[39] = SSL_INIT;
        astatus[40] = SSL_CONNECT;
        astatus[41] = SSL_VERIFY;
        astatus[42] = EXTERNAL_THREAD;
        astatus[43] = CRYPTO_ERROR;
        astatus[44] = CRYPTO_TRUNCATED;
        astatus[45] = CRYPTO_KEY_UNAVAILABLE;
        astatus[46] = BAD_HOSTNAME;
        astatus[47] = CRYPTO_KEY_UNUSABLE;
        astatus[48] = EMPTY_KEY_BLOB;
        astatus[49] = CORRUPT_KEYBLOB;
        astatus[50] = INVALID_KEY_ENCODING;
        astatus[51] = DEAD_THREAD;
        astatus[52] = THREAD_RUNNING;
        astatus[53] = THREAD_STOPPING;
        astatus[54] = BAD_STRING_ENCODING;
        astatus[55] = CRYPTO_INSUFFICIENT_SECURITY;
        astatus[56] = CRYPTO_ILLEGAL_PARAMETERS;
        astatus[57] = CRYPTO_HASH_UNINITIALIZED;
        astatus[58] = THREAD_NO_WAIT;
        astatus[59] = TIMER_EXITING;
        astatus[60] = INVALID_GUID;
        astatus[61] = THREADPOOL_EXHAUSTED;
        astatus[62] = THREADPOOL_STOPPING;
        astatus[63] = INVALID_STREAM;
        astatus[64] = TIMER_FULL;
        astatus[65] = IODISPATCH_STOPPING;
        astatus[66] = SLAP_INVALID_PACKET_LEN;
        astatus[67] = SLAP_HDR_CHECKSUM_ERROR;
        astatus[68] = SLAP_INVALID_PACKET_TYPE;
        astatus[69] = SLAP_LEN_MISMATCH;
        astatus[70] = SLAP_PACKET_TYPE_MISMATCH;
        astatus[71] = SLAP_CRC_ERROR;
        astatus[72] = SLAP_ERROR;
        astatus[73] = SLAP_OTHER_END_CLOSED;
        astatus[74] = NONE;
        astatus[75] = BUS_ERRORS;
        astatus[76] = BUS_READ_ERROR;
        astatus[77] = BUS_WRITE_ERROR;
        astatus[78] = BUS_BAD_VALUE_TYPE;
        astatus[79] = BUS_BAD_HEADER_FIELD;
        astatus[80] = BUS_BAD_SIGNATURE;
        astatus[81] = BUS_BAD_OBJ_PATH;
        astatus[82] = BUS_BAD_MEMBER_NAME;
        astatus[83] = BUS_BAD_INTERFACE_NAME;
        astatus[84] = BUS_BAD_ERROR_NAME;
        astatus[85] = BUS_BAD_BUS_NAME;
        astatus[86] = BUS_NAME_TOO_LONG;
        astatus[87] = BUS_BAD_LENGTH;
        astatus[88] = BUS_BAD_VALUE;
        astatus[89] = BUS_BAD_HDR_FLAGS;
        astatus[90] = BUS_BAD_BODY_LEN;
        astatus[91] = BUS_BAD_HEADER_LEN;
        astatus[92] = BUS_UNKNOWN_SERIAL;
        astatus[93] = BUS_UNKNOWN_PATH;
        astatus[94] = BUS_UNKNOWN_INTERFACE;
        astatus[95] = BUS_ESTABLISH_FAILED;
        astatus[96] = BUS_UNEXPECTED_SIGNATURE;
        astatus[97] = BUS_INTERFACE_MISSING;
        astatus[98] = BUS_PATH_MISSING;
        astatus[99] = BUS_MEMBER_MISSING;
        astatus[100] = BUS_REPLY_SERIAL_MISSING;
        astatus[101] = BUS_ERROR_NAME_MISSING;
        astatus[102] = BUS_INTERFACE_NO_SUCH_MEMBER;
        astatus[103] = BUS_NO_SUCH_OBJECT;
        astatus[104] = BUS_OBJECT_NO_SUCH_MEMBER;
        astatus[105] = BUS_OBJECT_NO_SUCH_INTERFACE;
        astatus[106] = BUS_NO_SUCH_INTERFACE;
        astatus[107] = BUS_MEMBER_NO_SUCH_SIGNATURE;
        astatus[108] = BUS_NOT_NUL_TERMINATED;
        astatus[109] = BUS_NO_SUCH_PROPERTY;
        astatus[110] = BUS_SET_WRONG_SIGNATURE;
        astatus[111] = BUS_PROPERTY_VALUE_NOT_SET;
        astatus[112] = BUS_PROPERTY_ACCESS_DENIED;
        astatus[113] = BUS_NO_TRANSPORTS;
        astatus[114] = BUS_BAD_TRANSPORT_ARGS;
        astatus[115] = BUS_NO_ROUTE;
        astatus[116] = BUS_NO_ENDPOINT;
        astatus[117] = BUS_BAD_SEND_PARAMETER;
        astatus[118] = BUS_UNMATCHED_REPLY_SERIAL;
        astatus[119] = BUS_BAD_SENDER_ID;
        astatus[120] = BUS_TRANSPORT_NOT_STARTED;
        astatus[121] = BUS_EMPTY_MESSAGE;
        astatus[122] = BUS_NOT_OWNER;
        astatus[123] = BUS_SET_PROPERTY_REJECTED;
        astatus[124] = BUS_CONNECT_FAILED;
        astatus[125] = BUS_REPLY_IS_ERROR_MESSAGE;
        astatus[126] = BUS_NOT_AUTHENTICATING;
        astatus[127] = BUS_NO_LISTENER;
        astatus[128] = BUS_BT_TRANSPORT_ERROR;
        astatus[129] = BUS_NOT_ALLOWED;
        astatus[130] = BUS_WRITE_QUEUE_FULL;
        astatus[131] = BUS_ENDPOINT_CLOSING;
        astatus[132] = BUS_INTERFACE_MISMATCH;
        astatus[133] = BUS_MEMBER_ALREADY_EXISTS;
        astatus[134] = BUS_PROPERTY_ALREADY_EXISTS;
        astatus[135] = BUS_IFACE_ALREADY_EXISTS;
        astatus[136] = BUS_ERROR_RESPONSE;
        astatus[137] = BUS_BAD_XML;
        astatus[138] = BUS_BAD_CHILD_PATH;
        astatus[139] = BUS_OBJ_ALREADY_EXISTS;
        astatus[140] = BUS_OBJ_NOT_FOUND;
        astatus[141] = BUS_CANNOT_EXPAND_MESSAGE;
        astatus[142] = BUS_NOT_COMPRESSED;
        astatus[143] = BUS_ALREADY_CONNECTED;
        astatus[144] = BUS_NOT_CONNECTED;
        astatus[145] = BUS_ALREADY_LISTENING;
        astatus[146] = BUS_KEY_UNAVAILABLE;
        astatus[147] = BUS_TRUNCATED;
        astatus[148] = BUS_KEY_STORE_NOT_LOADED;
        astatus[149] = BUS_NO_AUTHENTICATION_MECHANISM;
        astatus[150] = BUS_BUS_ALREADY_STARTED;
        astatus[151] = BUS_BUS_NOT_STARTED;
        astatus[152] = BUS_KEYBLOB_OP_INVALID;
        astatus[153] = BUS_INVALID_HEADER_CHECKSUM;
        astatus[154] = BUS_MESSAGE_NOT_ENCRYPTED;
        astatus[155] = BUS_INVALID_HEADER_SERIAL;
        astatus[156] = BUS_TIME_TO_LIVE_EXPIRED;
        astatus[157] = BUS_HDR_EXPANSION_INVALID;
        astatus[158] = BUS_MISSING_COMPRESSION_TOKEN;
        astatus[159] = BUS_NO_PEER_GUID;
        astatus[160] = BUS_MESSAGE_DECRYPTION_FAILED;
        astatus[161] = BUS_SECURITY_FATAL;
        astatus[162] = BUS_KEY_EXPIRED;
        astatus[163] = BUS_CORRUPT_KEYSTORE;
        astatus[164] = BUS_NO_CALL_FOR_REPLY;
        astatus[165] = BUS_NOT_A_COMPLETE_TYPE;
        astatus[166] = BUS_POLICY_VIOLATION;
        astatus[167] = BUS_NO_SUCH_SERVICE;
        astatus[168] = BUS_TRANSPORT_NOT_AVAILABLE;
        astatus[169] = BUS_INVALID_AUTH_MECHANISM;
        astatus[170] = BUS_KEYSTORE_VERSION_MISMATCH;
        astatus[171] = BUS_BLOCKING_CALL_NOT_ALLOWED;
        astatus[172] = BUS_SIGNATURE_MISMATCH;
        astatus[173] = BUS_STOPPING;
        astatus[174] = BUS_METHOD_CALL_ABORTED;
        astatus[175] = BUS_CANNOT_ADD_INTERFACE;
        astatus[176] = BUS_CANNOT_ADD_HANDLER;
        astatus[177] = BUS_KEYSTORE_NOT_LOADED;
        astatus[178] = BUS_NO_SUCH_HANDLE;
        astatus[179] = BUS_HANDLES_NOT_ENABLED;
        astatus[180] = BUS_HANDLES_MISMATCH;
        astatus[181] = BT_MAX_CONNECTIONS_USED;
        astatus[182] = BUS_NO_SESSION;
        astatus[183] = BUS_ELEMENT_NOT_FOUND;
        astatus[184] = BUS_NOT_A_DICTIONARY;
        astatus[185] = BUS_WAIT_FAILED;
        astatus[186] = BUS_BAD_SESSION_OPTS;
        astatus[187] = BUS_CONNECTION_REJECTED;
        astatus[188] = DBUS_REQUEST_NAME_REPLY_PRIMARY_OWNER;
        astatus[189] = DBUS_REQUEST_NAME_REPLY_IN_QUEUE;
        astatus[190] = DBUS_REQUEST_NAME_REPLY_EXISTS;
        astatus[191] = DBUS_REQUEST_NAME_REPLY_ALREADY_OWNER;
        astatus[192] = DBUS_RELEASE_NAME_REPLY_RELEASED;
        astatus[193] = DBUS_RELEASE_NAME_REPLY_NON_EXISTENT;
        astatus[194] = DBUS_RELEASE_NAME_REPLY_NOT_OWNER;
        astatus[195] = DBUS_START_REPLY_ALREADY_RUNNING;
        astatus[196] = ALLJOYN_BINDSESSIONPORT_REPLY_ALREADY_EXISTS;
        astatus[197] = ALLJOYN_BINDSESSIONPORT_REPLY_FAILED;
        astatus[198] = ALLJOYN_JOINSESSION_REPLY_NO_SESSION;
        astatus[199] = ALLJOYN_JOINSESSION_REPLY_UNREACHABLE;
        astatus[200] = ALLJOYN_JOINSESSION_REPLY_CONNECT_FAILED;
        astatus[201] = ALLJOYN_JOINSESSION_REPLY_REJECTED;
        astatus[202] = ALLJOYN_JOINSESSION_REPLY_BAD_SESSION_OPTS;
        astatus[203] = ALLJOYN_JOINSESSION_REPLY_FAILED;
        astatus[204] = ALLJOYN_LEAVESESSION_REPLY_NO_SESSION;
        astatus[205] = ALLJOYN_LEAVESESSION_REPLY_FAILED;
        astatus[206] = ALLJOYN_ADVERTISENAME_REPLY_ALREADY_ADVERTISING;
        astatus[207] = ALLJOYN_ADVERTISENAME_REPLY_FAILED;
        astatus[208] = ALLJOYN_CANCELADVERTISENAME_REPLY_FAILED;
        astatus[209] = ALLJOYN_FINDADVERTISEDNAME_REPLY_ALREADY_DISCOVERING;
        astatus[210] = ALLJOYN_FINDADVERTISEDNAME_REPLY_FAILED;
        astatus[211] = ALLJOYN_CANCELFINDADVERTISEDNAME_REPLY_FAILED;
        astatus[212] = BUS_UNEXPECTED_DISPOSITION;
        astatus[213] = BUS_INTERFACE_ACTIVATED;
        astatus[214] = ALLJOYN_UNBINDSESSIONPORT_REPLY_BAD_PORT;
        astatus[215] = ALLJOYN_UNBINDSESSIONPORT_REPLY_FAILED;
        astatus[216] = ALLJOYN_BINDSESSIONPORT_REPLY_INVALID_OPTS;
        astatus[217] = ALLJOYN_JOINSESSION_REPLY_ALREADY_JOINED;
        astatus[218] = BUS_SELF_CONNECT;
        astatus[219] = BUS_SECURITY_NOT_ENABLED;
        astatus[220] = BUS_LISTENER_ALREADY_SET;
        astatus[221] = BUS_PEER_AUTH_VERSION_MISMATCH;
        astatus[222] = ALLJOYN_SETLINKTIMEOUT_REPLY_NOT_SUPPORTED;
        astatus[223] = ALLJOYN_SETLINKTIMEOUT_REPLY_NO_DEST_SUPPORT;
        astatus[224] = ALLJOYN_SETLINKTIMEOUT_REPLY_FAILED;
        astatus[225] = ALLJOYN_ACCESS_PERMISSION_WARNING;
        astatus[226] = ALLJOYN_ACCESS_PERMISSION_ERROR;
        astatus[227] = BUS_DESTINATION_NOT_AUTHENTICATED;
        astatus[228] = BUS_ENDPOINT_REDIRECTED;
        astatus[229] = BUS_AUTHENTICATION_PENDING;
        astatus[230] = BUS_NOT_AUTHORIZED;
        astatus[231] = PACKET_BUS_NO_SUCH_CHANNEL;
        astatus[232] = PACKET_BAD_FORMAT;
        astatus[233] = PACKET_CONNECT_TIMEOUT;
        astatus[234] = PACKET_CHANNEL_FAIL;
        astatus[235] = PACKET_TOO_LARGE;
        astatus[236] = PACKET_BAD_PARAMETER;
        astatus[237] = PACKET_BAD_CRC;
        astatus[238] = STUN_ATTR_SIZE_MISMATCH;
        astatus[239] = STUN_AUTH_CHALLENGE;
        astatus[240] = STUN_SOCKET_NOT_OPEN;
        astatus[241] = STUN_SOCKET_OPEN;
        astatus[242] = STUN_FAILED_TO_SEND_MSG;
        astatus[243] = STUN_FRAMING_ERROR;
        astatus[244] = STUN_INVALID_ERROR_CODE;
        astatus[245] = STUN_INVALID_FINGERPRINT;
        astatus[246] = STUN_INVALID_ADDR_FAMILY;
        astatus[247] = STUN_INVALID_MESSAGE_INTEGRITY;
        astatus[248] = STUN_INVALID_MSG_TYPE;
        astatus[249] = STUN_INVALID_ATTR_TYPE;
        astatus[250] = STUN_RESPONSE_WITH_USERNAME;
        astatus[251] = STUN_ERR400_BAD_REQUEST;
        astatus[252] = STUN_BAD_INDICATION;
        astatus[253] = STUN_ERR401_UNAUTHORIZED_REQUEST;
        astatus[254] = STUN_TOO_MANY_ATTRIBUTES;
        astatus[255] = STUN_DUPLICATE_ATTRIBUTE;
        astatus[256] = STUN_UNAUTHORIZED_INDICATION;
        astatus[257] = ICE_ALLOCATING_MEMORY;
        astatus[258] = ICE_CHECKS_INCOMPLETE;
        astatus[259] = ICE_ALLOCATE_REJECTED_NO_RESOURCES;
        astatus[260] = ICE_ALLOCATION_QUOTA_REACHED;
        astatus[261] = ICE_ALLOCATION_MISMATCH;
        astatus[262] = ICE_STUN_ERROR;
        astatus[263] = ICE_INVALID_STATE;
        astatus[264] = ICE_UNKNOWN_COMPONENT_ID;
        astatus[265] = RENDEZVOUS_SERVER_DEACTIVATED_USER;
        astatus[266] = RENDEZVOUS_SERVER_UNKNOWN_USER;
        astatus[267] = UNABLE_TO_CONNECT_TO_RENDEZVOUS_SERVER;
        astatus[268] = NOT_CONNECTED_TO_RENDEZVOUS_SERVER;
        astatus[269] = UNABLE_TO_SEND_MESSAGE_TO_RENDEZVOUS_SERVER;
        astatus[270] = INVALID_RENDEZVOUS_SERVER_INTERFACE_MESSAGE;
        astatus[271] = INVALID_PERSISTENT_CONNECTION_MESSAGE_RESPONSE;
        astatus[272] = INVALID_ON_DEMAND_CONNECTION_MESSAGE_RESPONSE;
        astatus[273] = INVALID_HTTP_METHOD_USED_FOR_RENDEZVOUS_SERVER_INTERFACE_MESSAGE;
        astatus[274] = RENDEZVOUS_SERVER_ERR500_INTERNAL_ERROR;
        astatus[275] = RENDEZVOUS_SERVER_ERR503_STATUS_UNAVAILABLE;
        astatus[276] = RENDEZVOUS_SERVER_ERR401_UNAUTHORIZED_REQUEST;
        astatus[277] = RENDEZVOUS_SERVER_UNRECOVERABLE_ERROR;
        astatus[278] = RENDEZVOUS_SERVER_ROOT_CERTIFICATE_UNINITIALIZED;
        astatus[279] = BUS_NO_SUCH_ANNOTATION;
        astatus[280] = BUS_ANNOTATION_ALREADY_EXISTS;
        astatus[281] = SOCK_CLOSING;
        astatus[282] = NO_SUCH_DEVICE;
        astatus[283] = P2P;
        astatus[284] = P2P_TIMEOUT;
        astatus[285] = P2P_NOT_CONNECTED;
        astatus[286] = BAD_TRANSPORT_MASK;
        astatus[287] = PROXIMITY_CONNECTION_ESTABLISH_FAIL;
        astatus[288] = PROXIMITY_NO_PEERS_FOUND;
        astatus[289] = BUS_OBJECT_NOT_REGISTERED;
        astatus[290] = P2P_DISABLED;
        astatus[291] = P2P_BUSY;
        astatus[292] = BUS_INCOMPATIBLE_DAEMON;
        astatus[293] = P2P_NO_GO;
        astatus[294] = P2P_NO_STA;
        astatus[295] = P2P_FORBIDDEN;
        astatus[296] = ALLJOYN_ONAPPSUSPEND_REPLY_FAILED;
        astatus[297] = ALLJOYN_ONAPPSUSPEND_REPLY_UNSUPPORTED;
        astatus[298] = ALLJOYN_ONAPPRESUME_REPLY_FAILED;
        astatus[299] = ALLJOYN_ONAPPRESUME_REPLY_UNSUPPORTED;
        astatus[300] = BUS_NO_SUCH_MESSAGE;
        astatus[301] = ALLJOYN_REMOVESESSIONMEMBER_REPLY_NO_SESSION;
        astatus[302] = ALLJOYN_REMOVESESSIONMEMBER_NOT_BINDER;
        astatus[303] = ALLJOYN_REMOVESESSIONMEMBER_NOT_MULTIPOINT;
        astatus[304] = ALLJOYN_REMOVESESSIONMEMBER_NOT_FOUND;
        astatus[305] = ALLJOYN_REMOVESESSIONMEMBER_INCOMPATIBLE_REMOTE_DAEMON;
        astatus[306] = ALLJOYN_REMOVESESSIONMEMBER_REPLY_FAILED;
        astatus[307] = BUS_REMOVED_BY_BINDER;
        astatus[308] = BAD_ANNOTATION;
        astatus[309] = INVALID_CONNECT_ARGS;
        astatus[310] = ALREADY_FINDING;
        astatus[311] = CANCELLED;
        astatus[312] = ALREADY_REGISTERED;
        $VALUES = astatus;
    }
}
