// Decompiled by Jad v1.5.8g. Copyright 2001 Pavel Kouznetsov.
// Jad home page: http://www.kpdus.com/jad.html
// Decompiler options: packimports(3) fieldsfirst noctor space 

package com.qualcomm.toq.base.utils;

import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Locale;

public class Constants
{
    public static final class EndPointEnum extends Enum
    {

        private static final EndPointEnum $VALUES[];
        public static final EndPointEnum LeftEarPiece;
        public static final EndPointEnum RightEarPiece;
        public static final EndPointEnum WD;
        private String displayName;

        public static EndPointEnum valueOf(String s)
        {
            return (EndPointEnum)Enum.valueOf(com/qualcomm/toq/base/utils/Constants$EndPointEnum, s);
        }

        public static EndPointEnum[] values()
        {
            return (EndPointEnum[])$VALUES.clone();
        }

        public String toString()
        {
            return displayName;
        }

        static 
        {
            WD = new EndPointEnum("WD", 0, 0);
            LeftEarPiece = new EndPointEnum("LeftEarPiece", 1, 1);
            RightEarPiece = new EndPointEnum("RightEarPiece", 2, 2);
            EndPointEnum aendpointenum[] = new EndPointEnum[3];
            aendpointenum[0] = WD;
            aendpointenum[1] = LeftEarPiece;
            aendpointenum[2] = RightEarPiece;
            $VALUES = aendpointenum;
        }

        private EndPointEnum(String s, int i, int j)
        {
            super(s, i);
            if (j == 0)
            {
                displayName = "Toq";
            } else
            {
                if (j == 1)
                {
                    displayName = "Left Headset";
                    return;
                }
                if (j == 2)
                {
                    displayName = "Right Headset";
                    return;
                }
            }
        }
    }


    public static final String A2DP_PROFILE_CONNECTED;
    public static final String A2DP_PROFILE_DISCONNECTED;
    public static final String ACCUWEATHER_API_KEY = "9fc4b35acecc407e95143c14579a2d84";
    public static final String ACCU_WEATHER_HOUR_TEMP_TYPE = "WEATHER_HOUR_TEMPARATURE";
    public static final String ACCU_WEATHER_MIN_MAX_TEMP_TYPE = "WEATHER_MIN_MAX_TEMPARATURE";
    public static final String ACTION_ACTIVITY_MONITORING_UPDATE;
    public static final String ACTION_ALOHA_STATE_CHANGE;
    public static final String ACTION_ASSOCIATE_WD_DEVICE;
    public static final String ACTION_BLUETOOTH_NOT_ENABLED;
    public static final String ACTION_BLUETOOTH_NOT_SUPPORTED;
    public static final String ACTION_BT_ADAPTER_STATE_CHANGE = "android.bluetooth.adapter.action.STATE_CHANGED";
    public static final String ACTION_CALL_STATE_IDLE;
    public static final String ACTION_CALL_STATE_OFF_HOOK;
    public static final String ACTION_CALL_STATE_RINGING;
    public static final String ACTION_CANCEL_CALL;
    public static final String ACTION_CANCEL_FIND_PHONE_REQUEST;
    public static final String ACTION_CONNECTION_STATE_CHANGE;
    public static final String ACTION_CONNECTION_STOPPED;
    public static final String ACTION_EAR_PIECE_A2DP_CONNECTION_STATE_CHANGED = "android.bluetooth.a2dp.profile.action.CONNECTION_STATE_CHANGED";
    public static final String ACTION_EAR_PIECE_A2DP_PLAYING_STATE_CHANGED = "android.bluetooth.a2dp.profile.action.PLAYING_STATE_CHANGED";
    public static final String ACTION_EAR_PIECE_CONNECTED;
    public static final String ACTION_EAR_PIECE_DISCONNECTED;
    public static final String ACTION_EAR_PIECE_HANDLE_MESSAGE_SERVICE;
    public static final String ACTION_EAR_PIECE_HFP_AUDIO_STATE_CHANGED = "android.bluetooth.headset.profile.action.AUDIO_STATE_CHANGED";
    public static final String ACTION_EAR_PIECE_HFP_CONNECTION_STATE_CHANGED = "android.bluetooth.headset.profile.action.CONNECTION_STATE_CHANGED";
    public static final String ACTION_EAR_PIECE_HFP_VENDOR_SPECIFIC_HEADSET_EVENT = "android.bluetooth.headset.action.VENDOR_SPECIFIC_HEADSET_EVENT";
    public static final String ACTION_EAR_PIECE_PROFILE_UPDATE;
    public static final String ACTION_EAR_PIECE_UI_UPDATE;
    public static final String ACTION_EP_CONFIG_STATE_UPDATE;
    public static final String ACTION_EP_MORE_HEADSETS_FOUND_UPDATE;
    public static final String ACTION_FIRMWARE_TRANSFER;
    public static final String ACTION_FIRMWARE_TRANSFER_PROGRESS;
    public static final String ACTION_FMS_FILE_TRANSFER_COMPLETED;
    public static final String ACTION_FMS_FILE_TRANSFER_FAILED;
    public static final String ACTION_FOUND_WD_REQUEST;
    public static final String ACTION_INITIATE_CALL;
    public static final String ACTION_INSTALLED_ADDON_APP;
    public static final String ACTION_LOCALE_CHANGE = "android.intent.action.LOCALE_CHANGED";
    public static final String ACTION_NEW_LOCATION_FOUND;
    public static final String ACTION_PHONE_WD_CONNECTED;
    public static final String ACTION_PHONE_WD_DISCONNECTED;
    public static final String ACTION_REMOTE_DEVICE_DISASSOCIATED;
    public static final String ACTION_SERVICE_STOPPED;
    public static final String ACTION_SMARTWATCH_APP_UPDATED;
    public static final String ACTION_SMARTWATCH_CANCEL_ALL_NOTIFICATION;
    public static final String ACTION_SMARTWATCH_CANCEL_NOTIFICATION;
    public static final String ACTION_SMARTWATCH_FMS_FILE_SYNCED;
    public static final String ACTION_SMARTWATCH_HANDLE_MESSAGE_SERVICE;
    public static final String ACTION_SMARTWATCH_VOLUME_MUSIC;
    public static final String ACTION_SPP_MESSAGE_ERROR;
    public static final String ACTION_TOQ_NOTIFICATION_ON_CLICK = "com.qualcomm.toq.smartwatch.action.TOQ_NOTIFICATION_ON_CLICK";
    public static final String ACTION_TOQ_NOTIFICATION_ON_DELETE = "com.qualcomm.toq.smartwatch.action.TOQ_NOTIFICATION_ON_DELETE";
    public static final String ACTION_UNINSTALLED_ADDON_APP;
    public static final String ACTION_VERSION_INFO;
    public static final String ACTION_WD_DEVICE_DISASSOCIATED;
    public static final int ACTIVITY_MONITORING_GOAL_POINTS_DEFAULT_VALUE = 10000;
    public static final String ACTIVITY_MONITORING_PREFS_FILE = "activity_monitoring_pref";
    public static final int ACTIVITY_PHONE = 30;
    public static final int ACTIVITY_WD = 31;
    public static final int AGENDA_EVENT_DAYS = 2;
    public static final String ALLJOYN_NOTIFICATION_SETTINGS_PREFS_FILE = "alljoyn_notification_settings_pref";
    public static final String ALL_CLOCK_JSON_ARRAY_KEY = "Clocks";
    public static final String ALL_CLOCK_JSON_FILE_NAME = "allclocks.json";
    public static final String AMBIENT_BACKUP = "AmbientBackUp";
    public static final int AMBIENT_FILE_PUSH_TIMER = 900;
    public static final String AMBIENT_IMAGES_FILE_PATH = "AMBIENT_IMAGES";
    public static final long AMBIENT_POLLING_TIMER = 0xdbba0L;
    public static final String AMBIENT_SHARED_PREFS_FILE = "ambient__pref";
    public static final String AMBIENT_TYPE = "ambient_type";
    public static final String AMBIENT_TYPE_STOCK = "stock";
    public static final String AMBIENT_TYPE_WEATHER = "weather";
    public static final String APPLET_MENU_PREFS_FILE = "applet_menu_pref";
    public static String APPLICATION_PACKAGE_NAME;
    public static final String APP_ACTIVITY_MONITORING_CONTROLLER = "ACTIVITY_MONITORING_CONTROLLER";
    public static final String APP_AGENDA_CONTROLLER = "AGENDA_CONTROLLER";
    public static final String APP_AMBIENT_CONTROLLER = "AMBIENT_CONTROLLER";
    public static final String APP_CALL_LOG_CONTROLLER = "CALL_LOG_CONTROLLER";
    public static final String APP_CLOCKSETTINGS_CONTROLLER = "CLOCKSETTINGS_CONTROLLER";
    public static final String APP_COMM_HUB_CONTROLLER = "COMMUNICATION_HUB_CONTROLLER";
    public static final String APP_CONTACT_CONTROLLER = "CONTACT_CONTROLLER";
    public static final String APP_EP_COMMUNICATION_CONTROLLER = "EP_COMMUNICATION_CONTROLLER";
    public static final String APP_FAVOURITE_APP_CONTROLLER = "FAVOURITE_APPS_CONTROLLER";
    public static final String APP_FIRMWARE_UPDATE_CONTROLLER = "FIRMWARE_UPDATE_CONTROLLER";
    public static final String APP_FMS_CONTROLLER = "FMS_CONTROLLER";
    public static final String APP_FTS_CONTROLLER = "FTS_CONTROLLER";
    public static final String APP_IMAGE = "AppImage";
    public static final String APP_LOGS_DIALOG_PREFS_FILE = "app_logs_dialog_pref";
    public static final int APP_LOG_PHONE = 34;
    public static final int APP_LOG_WD = 35;
    public static final int APP_MSG_PHONE = 26;
    public static final int APP_MSG_WD = 27;
    public static final String APP_POPUP_CONTROLLER = "POPUP_CONTROLLER";
    public static final String APP_SHARED_PREFS_FILE = "app_pref";
    public static final String APP_SMS_CONTROLLER = "SMS_CONTROLLER";
    public static final String APP_SPEECH_CONTROLLER = "SPEECH_CONTROLLER";
    public static final String APP_STORAGE_SERVICE_CONTROLLER = "STORAGE_SERVICE_CONTROLLER";
    public static final String APP_SYSTEM_CONTROLLER = "TIME_CONTROLLER";
    public static final String APP_USERSETTINGS_CONTROLLER = "USER_SETTINGS_CONTROLLER";
    public static final String APP_VERSION_CONTROLLER = "VERSION_CONTROLLER";
    public static final String APP_VOICE_CALL_CONTROLLER = "VOICE_CALL_CONTROLLER";
    public static final String ASSOCIATED_DEVICE_SHARED_PREFS_FILE = "associated_device_pref";
    public static final String AVAILABLE_DEVICES = "Available devices";
    public static final String AVAILABLE_DEVICES_BOND_STATE = "BondState";
    public static final int ActivateVRReq = 2;
    public static final int ActivateVRResp = 16386;
    public static final int ActivityUpdateInd = 32768;
    public static final int ActivityUpdateReq = 0;
    public static final int ActivityUpdateResp = 16384;
    public static final int AddDirectedMessageInd = 32768;
    public static final int AlohaVersionContinueInd = 1;
    public static final int AlohaVersionInd = 0;
    public static final int AlohaVersionWaitUpdateInd = 2;
    public static final int AnswerCallReq = 5;
    public static final int AnswerCallResp = 16389;
    public static final String BATTERY_IND_NAME = "name";
    public static final String BATTERY_IND_PERCENTAGE = "percentage";
    public static final int BT_STATE_OFF_NOTIFICATION_ID = 10;
    public static final String BUILD_TYPE = "release";
    public static final int BUILD_VARIANT_BOTH = 2;
    public static final int BUILD_VARIANT_TOQ_EARPIECE = 1;
    public static final int BUILD_VARIANT_TOQ_SMARTWATCH = 0;
    public static final String BUNDLE_KEY = "bundle";
    public static final int BatteryInd = 4;
    public static final String CALENDARS_SHARED_PREFS_FILE = "calendars_pref";
    public static final String CALENDAR_ACCESS_LEVEL = "700";
    public static final String CC_WEATHER_TIMER_INTERVAL = "cc_weather_timer_interval";
    public static final String CELSIUS_TEMPERATURE_UNIT = "Celsius";
    public static final int CHECK_COMPATIBILITY_VALUE = 0;
    public static final String CLOCKS_APP_ZIP_LOCATION = "/packages/%s/app.zip";
    public static final String CLOCK_ACTIVITY = "Activity";
    public static final String CLOCK_AGENDA = "Agenda";
    public static final String CLOCK_BLOSSOM = "Blossom";
    public static final String CLOCK_BOLD = "Bold";
    public static final String CLOCK_BUILTIN = "builtin";
    public static final String CLOCK_CALENDAR = "Calendar";
    public static final String CLOCK_CALYPSO = "Calypso";
    public static final String CLOCK_CLASSIC = "Classic";
    public static final int CLOCK_DEFAULT_SELECTION_COUNT = 5;
    public static final String CLOCK_DEGREES = "Degrees";
    public static final String CLOCK_DISPLAY_NAME_KEY = "displayName";
    public static final String CLOCK_DIVER = "Diver";
    public static final String CLOCK_DYNAMIC = "dynamic";
    public static final String CLOCK_FACETS = "Facets";
    public static final String CLOCK_FALL_LEAVES = "Fall Leaves";
    public static final String CLOCK_FLIP = "Flip";
    public static final String CLOCK_GAUGE = "Gauge";
    public static final String CLOCK_IMAGE_PATH = "/Clocks";
    public static final String CLOCK_INFO_APP_ZIP_NAME = "appZipName";
    public static final String CLOCK_INFO_ASSET_FILE_NAME = "assetFileName";
    public static final String CLOCK_INFO_ASSET_KEY = "asset";
    public static final String CLOCK_INFO_ICON_KEY = "icon";
    public static final String CLOCK_INFO_JSON_NAME_KEY = "jsonName";
    public static final String CLOCK_INFO_PACKAGE_NAME = "packageName";
    public static final String CLOCK_INFO_TYPE_NAME = "clockType";
    public static final String CLOCK_INTERSECTION = "Intersection";
    public static final String CLOCK_JSON_ARRAY_KEY = "Clock";
    public static final String CLOCK_JSON_FILE_NAME = "clock.json";
    public static final String CLOCK_LAYERS = "Layers";
    public static final int CLOCK_MAX_SELECTION_COUNT = 8;
    public static final String CLOCK_PACKAGE_NAME = "clock_package_name";
    public static final String CLOCK_PRISM = "Prism";
    public static final String CLOCK_RING = "Ring";
    public static final String CLOCK_SETTINGS_PREFS_FILE = "clock_settings_pref";
    public static final String CLOCK_STOCK = "Stocks";
    public static final int CLOCK_THREE_IMAGE_LIMIT = 3;
    public static final String CLOCK_THREE_ZIP_LOCATION = "/res/apps/ClockThree.zip";
    public static final String CLOCK_TILE = "Tile";
    public static final String CLOCK_TYPE = "clock_type";
    public static final String CLOCK_TYPE_KEY = "type";
    public static final String CLOCK_TYPOGRAPHIC = "Typographic";
    public static final String CLOCK_WEATHER = "Weather";
    public static final String CLOCK_WEATHER_GRID = "Weather Grid";
    public static final String CLOCK_WORLD = "World Time";
    public static final int COMM_ENDPOINT_EPCOMM_EP = 20;
    public static final int COMM_ENDPOINT_EPCOMM_FROM_SECONDARY_EP_IN_OPERATIONAL = 23;
    public static final int COMM_ENDPOINT_EPCOMM_PHONE = 19;
    public static final int COMM_ENDPOINT_EPCOMM_TO_SECONDARY_EP_IN_OPERATIONAL = 22;
    public static final int COMM_ENDPOINT_FMS_PHONE = 17;
    public static final int COMM_ENDPOINT_FMS_WD = 18;
    public static final int COMM_ENDPOINT_POPUP_PHONE = 7;
    public static final int COMM_ENDPOINT_POPUP_WD = 8;
    public static final int COMM_ENDPOINT_SYNC_PHONE = 9;
    public static final int COMM_ENDPOINT_SYNC_WD = 10;
    public static final String COMPANY_NAME = "QUALCOMM INC COM";
    public static final long CONNECTION_LOOPER_DELAY = 5000L;
    public static final String CONST_ADMIN_AREA = "AdministrativeArea";
    public static final String CONST_COUNTRY = "Country";
    public static final String CONST_ENGLISH_NAME = "EnglishName";
    public static final String CONST_KEY = "Key";
    public static final String CONST_LOCALIZED_NAME = "LocalizedName";
    public static final String CURRENT_CITY = "CurrentCity";
    public static final String CURRENT_CITY_LAST_UPDATE_TIME = "current_city_last_update_time";
    public static final String CURRENT_CITY_TEMPERATURE_UNIT_CHANGED = "current_city_temp_unit_changed";
    public static final String CURRENT_CITY_WEATHER = "CurrentCityWeather";
    public static String CURRENT_MAC_ADDR = "00:15:83:15:A3:10";
    public static final int CalendarCreatePopupReq = 10;
    public static final int CalendarCreatePopupResp = 13;
    public static final int CalendarDestroyPopupReq = 12;
    public static final int CalendarDestroyPopupResp = 15;
    public static final int CalendarId = 9;
    public static final int CalendarPopupInd = 16;
    public static final int CalendarUpdatePopupReq = 11;
    public static final int CalendarUpdatePopupResp = 14;
    public static final int Call_Held_Code_Both = 1;
    public static final int Call_Held_Code_No_Call = 0;
    public static final int Call_Held_Code_One = 2;
    public static final int Call_Setup_Status_Code_Incoming = 1;
    public static final int Call_Setup_Status_Code_No_Call = 0;
    public static final int Call_Setup_Status_Code_Outgoing = 2;
    public static final int Call_Status_Code_No_Call = 0;
    public static final int Call_Status_Code_One_Call = 1;
    public static final int CancelFindPhoneReq = 2;
    public static final int CancelFindPhoneResp = 16386;
    public static final int CancelFindWDReq = 5;
    public static final int CancelFindWDResp = 16389;
    public static final int CancelOutgoingCallReq = 4;
    public static final int CancelOutgoingCallResp = 16388;
    public static final int CancelVRReq = 3;
    public static final int CancelVRResp = 16387;
    public static final int ChangeModeRequestInd = 1;
    public static final int ChangeRoleRequest = 2;
    public static final int ChangeRoleResponse = 3;
    public static final int CreatePopupReq = 0;
    public static final int CreatePopupResp = 16384;
    public static final String DATA_ERROR = "Unable to update data";
    public static final int DATA_TRANSFER_10K = 10;
    public static final int DATA_TRANSFER_20K = 20;
    public static final int DATA_TRANSFER_30K = 30;
    public static final String DAY_BAR_CHART_TYPE = "day_bar_chart";
    public static final String DEFAULT = "Default";
    public static final String DEFAULT_ADMIN = "Default Admin,Default Country";
    public static final String DEFAULT_CITY = "San Diego";
    public static final String DEFAULT_CITY_ADMIN_AREA = "CA";
    public static final String DEFAULT_EP_LINK_KEY1 = "00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00";
    public static final int DEFAULT_GOAL_REMINDER_SIX_PM = 18;
    public static final int DEFAULT_GOAL_REMINDER_TEN_AM = 10;
    public static final int DEFAULT_GOAL_REMINDER_TWO_PM = 14;
    public static final String DEFAULT_LANGUAGE_ENGLISH = "en_US";
    public static final String DEFAULT_STOCK = "QCOM";
    public static final String DEGREES_CLOCK_DAT = "temperature.dat";
    public static final String DEGREES_CLOCK_DAT_LOCATION = "/packages/com.qualcomm.qce.degreesclock/temperature.dat";
    public static final String DEGREES_CLOCK_JSON_NAME = "com.qualcomm.qce.degreesclock/Degrees";
    public static final String DEGREES_CLOCK_TYPE = "DegreesClock";
    public static final String DEGREE_SIGN = "\260";
    public static final int DEST_ADDRESS[] = {
        0, 1, 3, 5, 7, 9, 15, 17, 19, 22, 
        24, 26, 28, 30, 32, 34
    };
    public static final String DEVICE_ADDRESS = "device_address";
    public static final String DEVICE_NAME = "device_name";
    public static final String DEVICE_PAIRED = "Paired";
    public static final String DEVICE_PAIRING = "Pairing";
    public static final String DEVICE_UNPAIRED = "Unpaired";
    public static final int DIALOG_EXIT_CHECK = 1;
    public static final int DIALOG_MAC_ADDR = 2;
    public static final int DISCOVERABLE_DURATION = 300;
    public static final int DISMISS_PROGRESS_DIALOG = 2;
    public static final int DISPLAY_LIST_10 = 0;
    public static final int DISPLAY_LIST_20 = 1;
    public static final int DISPLAY_LIST_30 = 2;
    public static final int DISPLAY_LIST_40 = 3;
    public static final int DISPLAY_PROGRESS_DIALOG = 1;
    public static final String DS_ADDR = "ds_addr";
    public static final String DS_BATTERY = "ds_battery";
    public static final String DS_NAME = "ds_name";
    public static final String DS_STATUS = "ds_status";
    public static final int DemoAJNotificationCreatePopupReq = 20;
    public static final int DemoAJNotificationCreatePopupResp = 23;
    public static final int DemoAJNotificationDestroyPopupResp = 25;
    public static final int DemoAJNotificationId = 20;
    public static final int DemoAJNotificationPopupInd = 26;
    public static final int DemoAJNotificationUpdatePopupResp = 24;
    public static final int DestroyPopupReq = 2;
    public static final int DestroyPopupResp = 16386;
    public static final int DialReq = 0;
    public static final int DialResp = 16384;
    public static final int DisassociateReq = 8;
    public static final int DisassociateResp = 16392;
    public static final int END_POINT_EP_LEFT = 1;
    public static final int END_POINT_EP_RIGHT = 2;
    public static final int END_POINT_TOQ = 0;
    public static String EP_STATUS_CONNECTING = "";
    public static String EP_STATUS_HAS_UPDATED_SW = "";
    public static final int EP_STATUS_LOW_BATTERY_STATE = 2020;
    public static String EP_STATUS_OK = "";
    public static String EP_STATUS_REBOOTING = "";
    public static final int EP_STATUS_SW_UPDATE_CHECKER = 2021;
    public static String EP_STATUS_UNABLE_CONNECT = "";
    public static String EP_STATUS_UNABLE_TO_SUPPORT = "";
    public static String EP_STATUS_UPDATE_COMPLETE = "";
    public static String EP_STATUS_UPDATE_FAILED = "";
    public static String EP_STATUS_UPDATE_REQUIRED = "";
    public static String EP_STATUS_WAITING = "";
    public static String EP_SUBSTATUS_REFRESH_STATUS = "";
    public static String EP_SUBSTATUS_UNABLE_CONNECT = "";
    public static String EP_SUBSTATUS_UNABLE_TO_SUPPORT = "";
    public static String EP_TAG = "EP_STATE_MACHINE";
    public static String EP_TFTP_PATH = "";
    public static final int ERROR_BLUETOOTH_NOT_ENABLED = 0;
    public static final int ERROR_DEVICE_MAKE_DISCOVERABLE = 2;
    public static final int ERROR_DEVICE_NOT_CONNECTED = 1;
    public static final long ERROR_WEATHER_AMBIENT_POLL_INTERVAL_MILLI = 0xdbba0L;
    public static final String EULA_DIALOG_CHECK_SHARED_PREFS_FILE = "eula_dialog_check_prefs";
    public static final String E_TRADE_CONSUMER_KEY = "f9269f0dbe43320e8143305cd0afdcfa";
    public static final String E_TRADE_CONSUMER_KEY_NAME = "ConsumerKey";
    public static final int EndCallReq = 7;
    public static final int EndCallResp = 16391;
    public static final String FAHRENHEIT_TEMPERATURE_UNIT = "Fahrenheit";
    public static final String FAVORITE_APPS_PREFS_FILE = "favorite_apps_pref";
    public static final String FAV_APP_ACTIVITY = "Activity";
    public static final String FAV_APP_ALARM = "Alarm";
    public static final String FAV_APP_CALENDER = "Calendar";
    public static final String FAV_APP_COMM_HUB = "Comm Hub";
    public static final String FAV_APP_MUSIC = "Music";
    public static final String FAV_APP_NOTIFICATIONS = "Notifications";
    public static final String FAV_APP_STATUS = "Status";
    public static final String FAV_APP_STOCKS = "Stocks";
    public static final String FAV_APP_WEATHER = "Weather";
    public static final String FIRST_TIME_CONNECTED_SHARED_PREFS_FILE = "first_time_connected_pref";
    public static final String FIRST_TIME_DISP_US_ENGLISH_QUICK_REPLY_KEY = "first_time_quick_reply_shown";
    public static final long FIVE_MINUTE_MILLISEC = 0x493e0L;
    public static final int FMSCleanupReq = 3;
    public static final int FMSCleanupResp = 16387;
    public static final int FMSDeleteReq = 2;
    public static final int FMSDeleteResp = 16386;
    public static final int FMSFileOpenFailInd = 32768;
    public static final int FMSFileTransferReq = 1;
    public static final int FMSFileTransferResp = 16385;
    public static final int FMSReSyncReq = 4;
    public static final int FMSReSyncResp = 16388;
    public static final int FMS_DELETE_REQUEST_SENT = 8;
    public static final int FMS_FILE_SYNC_FAILED_PRIORITY = 100;
    public static final String FMS_FOLDER_PATH = "/fms";
    public static final int FMS_INVALID = -1;
    public static final int FMS_MARKED_FOR_DELETION = 7;
    public static final int FMS_MAX_REQUEST_MESSAGE_SENT = 3;
    public static final String FMS_MUSIC_PLAYLIST_PATH = "/musicplayer/playlist.jsn";
    public static final int FMS_READY_TO_TRANSFER = 3;
    public static final long FMS_RESPONSE_MAX_WAIT_TIME = 0x493e0L;
    public static final long FMS_RESPONSE_WAIT_TIME = 30000L;
    public static final long FMS_STATE_TIMER_INTERVAL = 30000L;
    public static final int FMS_SYNCED = 6;
    public static final int FMS_TRANSFER_COMPLETE = 5;
    public static final String FMS_TRANSFER_FOLDER_PATH = "/transfer";
    public static final int FMS_TRANSFER_IN_PROGRESS = 4;
    public static final int FROYO_BUILDCODE = 8;
    public static String FTP_CUSTOM_UUID = "00000001476D42C4BD119D377C456951";
    public static String FTP_STANDARD_UUID;
    public static String FTP_UUID;
    public static final int FTS_PHONE = 32;
    public static final int FTS_WD = 33;
    public static final int FindPhoneReq = 1;
    public static final int FindPhoneResp = 16385;
    public static final int FindWDReq = 4;
    public static final int FindWDResp = 16388;
    public static final int FoundPhoneReq = 3;
    public static final int FoundPhoneResp = 16387;
    public static final int FoundWDReq = 6;
    public static final int FoundWDResp = 16390;
    public static final int FtsGetReq = 0;
    public static final int FtsGetResp = 16384;
    public static final int FtsSendReq = 1;
    public static final int FtsSendResp = 16385;
    public static final int GB_BUILDCODE = 10;
    public static final String GENERATE_CLOCK_FILE = "generate_world_clock_file";
    public static final String GENERIC_LOG_APPENDER_NAME = "genericlog_appender";
    public static final String GENERIC_LOG_TYPE = "generic_log";
    public static final String GOOG_STOCK_TYPE = "GOOG_STOCK_TYPE";
    public static final String GO_SMS_PACKAGE_NAME = "com.jb.gosms";
    public static final int GetActivityReq = 0;
    public static final int GetActivityResp = 16384;
    public static final int GetPhoneStateReq = 15;
    public static final int GetPhoneStateResp = 16399;
    public static final int GetTimeReq = 0;
    public static final int GetTimeResp = 16384;
    public static final int GetWDBatteryLevelReq = 9;
    public static final int GetWDBatteryLevelResp = 16393;
    public static final String HARDWARE_REVISION_EP_A3 = "A3";
    public static final String HARDWARE_REVISION_EP_MP = "MP";
    public static final String HARDWARE_REVISION_EP_P0 = "P0";
    public static final String HARDWARE_REVISION_EP_P1 = "P1";
    public static final String HARDWARE_REVISION_EP_P2 = "P2";
    public static final String HFP_PROFILE_CONNECTED;
    public static final String HFP_PROFILE_DISCONNECTED;
    public static final String ICON_AURORA = "Aurora";
    public static final String ICON_INNOVA = "Innova";
    public static final String ICON_LUMINOUS = "Luminous";
    public static final String ICON_OPTIMA = "Optima";
    public static final String ICON_SOLAR = "Solar";
    public static final String ICON_VIBRANT = "Vibrant";
    public static final int ICS_BUILDCODE = 14;
    public static final String ICS_INTENT_ACTION_INSTALL_PACKAGE = "android.intent.action.INSTALL_PACKAGE";
    public static final String ICS_INTENT_EXTRA_ALLOW_REPLACE = "android.intent.extra.ALLOW_REPLACE";
    public static final String IMG_99 = "99.img";
    public static final String IMG_FORMAT_EXTENSION = ".img";
    public static final String IND_ALOHA_VERSION = "AlohaVersion";
    public static final String IND_BUILD_TARGET = "BuildTarget";
    public static final String IND_CALLER_ID = "caller_id";
    public static final String IND_CALLER_ID_PRESENT = "caller_id_present";
    public static final String IND_CALLER_ID_TYPE = "caller_id_type";
    public static final String IND_CALLER_NAME = "caller_name";
    public static final String IND_CALL_HELD = "call_held";
    public static final String IND_CALL_SETUP_STATUS = "call_setup_status";
    public static final String IND_CALL_STATUS = "call_status";
    public static final String IND_CALL_TIME = "call_time";
    public static final String IND_CCA_ID = "CCA_Id";
    public static final String IND_HARDWARE_REVISION = "HardwareRevision";
    public static final String IND_ITEM_ID = "item_id";
    public static final String IND_MIC_MUTE = "mic_mute";
    public static final String IND_MUSIC_ALBUM = "album";
    public static final String IND_MUSIC_ALBUM_ART = "album-art";
    public static final String IND_MUSIC_ARTIST = "artist";
    public static final String IND_MUSIC_CONTROL_FLAG = "control-flag";
    public static final String IND_MUSIC_SEEK = "seek";
    public static final String IND_MUSIC_STATE = "state";
    public static final String IND_MUSIC_TITLE = "title";
    public static final String IND_PHONE_TYPE = "PhoneType";
    public static final String IND_POPUP_DISMISSED = "dismissed";
    public static final String IND_POPUP_EVENT = "event";
    public static final String IND_POPUP_ID = "popup_id";
    public static final String IND_PRIVILEGED = "privileged";
    public static final String IND_PRODUCT_ID = "ProductId";
    public static final String IND_PRODUCT_MODEL = "ProductModel";
    public static final String IND_PRODUCT_NAME = "ProductName";
    public static final String IND_SERVICE = "service";
    public static final String IND_SOFTWARE_RELEASE = "SoftwareRelease";
    public static final String IND_SOFTWARE_REVISION = "SoftwareRevision";
    public static final String IND_SPEECH_STATUS = "status";
    public static final String IND_SPEECH_TEXT = "text";
    public static final String IND_TEXT = "text";
    public static final String IND_TIME = "time";
    public static final String IND_TIME_DST = "dst";
    public static final String IND_TIME_EPOCHTIME = "epoch_time";
    public static final String IND_TIME_TIMEZONE = "time_zone";
    public static final String IND_TRANSPORT_PROTOCOL = "TransportProtocol";
    public static final String IND_WIDGET_ID = "widget_id";
    public static final String ISSUE_LOGGER_DEFAULT_EMAIL = "phub.errorlog@qualcomm.com";
    public static final int ISSUE_LOGGER_FILE_SIZE_IN_KB = 200;
    public static final String IS_TIMER_POLL = "isTimerPoll";
    public static final int IncomingSMSInd = 32768;
    public static final int JELLY_BEAN_MR1_BUILDCODE = 17;
    public static final String KEY_ACTIVITY_CURRENT_DAY_END = "activity_current_day_end";
    public static final String KEY_ACTIVITY_FINAL_POINTS = "activity_final_points";
    public static final String KEY_ACTIVITY_GOAL_REMINDER_SWITCH_STATE = "activity_goal_reminder_switch_state_key";
    public static final String KEY_ACTIVITY_GOAL_REMINDER_TIMES_SET = "activity_goal_reminder_times_set_key";
    public static final String KEY_ACTIVITY_INITIAL_PROGRESS = "activity_initial_progress";
    public static final String KEY_ACTIVITY_LAST_EPOC_TIME = "activity_last_epoc_time";
    public static final String KEY_ACTIVITY_LAST_RECEIVED_CURRENTDAY_OFFSET = "activity_last_received_currentday_offset";
    public static final String KEY_ACTIVITY_LAST_RECEIVED_CURRENT_COUNT = "activity_last_received_current_count";
    public static final String KEY_ACTIVITY_LAST_RECEIVED_CURRENT_OFFSET = "activity_last_received_current_offset";
    public static final String KEY_ACTIVITY_LAST_RECEIVED_FINAL_POINTS = "activity_last_received_final_points";
    public static final String KEY_ACTIVITY_LAST_RECEIVED_POINTS = "activity_last_received_points";
    public static final String KEY_ACTIVITY_MONITORING_GOAL_POINTS = "activity_monitoring_goal_points_key";
    public static final String KEY_ACTIVITY_MONITORING_KEY_VALUE = "activity_monitoring_key_value";
    public static final String KEY_ACTIVITY_MONITORING_NEW_KEY_VALUE = "activity_monitoring_new_key_value";
    public static final String KEY_ACTIVITY_MONITORING_SETTINGS_BUTTON_CHECKED = "activity_monitoring_settings_toggle_key";
    public static final String KEY_ACTIVITY_MONITORING_UI_VALUE = "activity_monitoring_ui_value";
    public static final String KEY_ACTIVITY_OFFSET_FINAL_POINTS = "activity_monitoring_offset_final_points";
    public static final String KEY_ACTIVITY_OFFSET_POINTS = "activity_monitoring_offset_points";
    public static final String KEY_ACTIVITY_RESET_DIFF_POINTS = "activity_reset_diff_points";
    public static final String KEY_ALLJOYN_NOTIFICATION_SETTINGS_BUTTON_CHECKED = "alljoyn_notification_settings_toggle_key";
    public static final String KEY_ALL_CALENDAR_ID = "all_calendar_id";
    public static final String KEY_APPLET_MENU_APP_DETAILS = "applet_menu_app_details";
    public static final String KEY_APP_LOGS_DIALOG_CHECKBOX_STATE = "app_logs_dialog_checkbox_key";
    public static final String KEY_ASSOCIATED_EP_COMMON_DEVICE_LINKKEY = "ep_common_device_linkkey";
    public static final String KEY_ASSOCIATED_EP_L_DEVICE_ADDRESS = "associated_ep_l_device_address";
    public static final String KEY_ASSOCIATED_EP_L_DEVICE_CONNECTED_EP = "ep_l_device_connected_ep";
    public static final String KEY_ASSOCIATED_EP_L_DEVICE_DEPENDENT_FLAG = "epLDependendentOnPrimaryFlag";
    public static final String KEY_ASSOCIATED_EP_L_DEVICE_LINKKEY = "ep_l_device_linkkey";
    public static final String KEY_ASSOCIATED_EP_L_DEVICE_MODE = "ep_l_device_mode";
    public static final String KEY_ASSOCIATED_EP_L_DEVICE_NAME = "associated_ep_l_device_name";
    public static final String KEY_ASSOCIATED_EP_L_DEVICE_ROLE = "ep_l_device_role";
    public static final String KEY_ASSOCIATED_EP_L_FORCE_UPGRADE_REQ_FLAG = "ep_l_force_upgrade_Flag";
    public static final String KEY_ASSOCIATED_EP_R_DEVICE_ADDRESS = "associated_ep_r_device_address";
    public static final String KEY_ASSOCIATED_EP_R_DEVICE_CONNECTED_EP = "ep_r_device_connected_ep";
    public static final String KEY_ASSOCIATED_EP_R_DEVICE_DEPENDENT_FLAG = "epRDependendentOnPrimaryFlag";
    public static final String KEY_ASSOCIATED_EP_R_DEVICE_LINKKEY = "ep_r_device_linkkey";
    public static final String KEY_ASSOCIATED_EP_R_DEVICE_MODE = "ep_r_device_mode";
    public static final String KEY_ASSOCIATED_EP_R_DEVICE_NAME = "associated_ep_r_device_name";
    public static final String KEY_ASSOCIATED_EP_R_DEVICE_ROLE = "ep_r_device_role";
    public static final String KEY_ASSOCIATED_EP_R_FORCE_UPGRADE_REQ_FLAG = "ep_r_force_upgrade_Flag";
    public static final String KEY_ASSOCIATED_TO_EP_BASS_BOOST_MODE = "ep_bass_boost_mode";
    public static final String KEY_ASSOCIATED_TO_EP_BATTERY_LEVEL = "ep_battery_level";
    public static final String KEY_ASSOCIATED_TO_EP_FIRMWARE_DATE = "ep_firmware_date";
    public static final String KEY_ASSOCIATED_TO_EP_FIRMWARE_VERSION = "ep_firmware_version";
    public static final String KEY_ASSOCIATED_WD_DEVICE_ADDRESS = "associated_wd_device_address";
    public static final String KEY_ASSOCIATED_WD_DEVICE_NAME = "associated_wd_device_name";
    public static final String KEY_BUILD_TARGET = "build_target";
    public static final String KEY_CLOCK_DATA = "clock_data";
    public static final String KEY_CLOCK_SETTINGS_DEGREE_STATE = "clock_degree_state";
    public static final String KEY_CLOCK_SETTINGS_STOCK_STATE = "clock_stock_state";
    public static final String KEY_CLOCK_SETTINGS_TYPES = "clock_settings_types";
    public static final String KEY_CLOCK_SETTINGS_WEATHER_GRID_STATE = "clock_weather_grid_state";
    public static final String KEY_CLOCK_SETTINGS_WORLD_CLOCK_STATE = "clock_world_state";
    public static final String KEY_DEVICE_NAME = "device_name";
    public static final String KEY_EULA_ACCEPTED = "eula_accepted";
    public static final String KEY_EULA_VERSION = "eula_version";
    public static final String KEY_FAVORITE_APP_TYPES = "favorite_apps_types";
    public static final String KEY_FIRST_TIME_CONNECTED = "first_time_connected";
    public static final String KEY_FMS_IS_CLEAN_REQUEST_SENT = "app_install_clean_fms";
    public static final String KEY_HARDWARE_REVISION = "hardware_revision";
    public static final String KEY_HEADSET_WELCOME_CARD_HIDDEN = "headset_welcome_card_hidden";
    public static final String KEY_LANGUAGE_SETTING_AUTO_BUTTON_CHECKED = "language_setting_auto_button_checked";
    public static final String KEY_MODEL_NUMBER = "model_number";
    public static final String KEY_NOTIFICATIONS_DATA = "notifications_data";
    public static final String KEY_NOTIFICATIONS_DECK_OF_CARDS = "notification_deck_of_cards_key";
    public static final String KEY_NOTIFICATION_SETTINGS = "notification_settings_key";
    public static final String KEY_NOTIFICATION_SETTINGS_FILTER_CHECKED = "notification_settings_filter_key";
    public static final String KEY_NO_EARPIECES_PAIRED_CARD = "no_earpieces_paired_card";
    public static final String KEY_PHUB_TCP_INTERFACE = "phub_tcp_address";
    public static final String KEY_PHUB_TCP_PORT = "phub_tcp_port";
    public static final String KEY_PREFERENCE_ADVANCED_GROUP = "preference_advanced_group_key";
    public static final String KEY_PREFERENCE_APPEARANCE_GROUP = "preference_appearance_group_key";
    public static final String KEY_PREFERENCE_APPLET_GROUP = "preference_applet_group_key";
    public static final String KEY_PREFERENCE_NOTIFICATION_GROUP = "preference_notification_group_key";
    public static final String KEY_QUICK_REPLY_US_ENGLISH = "qr";
    public static final String KEY_SERIAL_NUMBER = "serial_number";
    public static final String KEY_SOFTWARE_RELEASE = "software_release";
    public static final String KEY_SOFTWARE_REVISION = "software_revision";
    public static final String KEY_TAKE_TOUR_HIDDEN = "take_tour_hidden";
    public static final String KEY_WHATS_NEW_CARD_HIDDEN = "whats_new_card_hidden_1_6";
    public static final String LANGUAGES = "Languages";
    public static final String LANGUAGE_TEXT_CHINESE = "zh_CN";
    public static final String LG_DEVICE_MANUFACTURE_NAME = "LGE";
    public static final String LOCALE_LIST_FILE_NAME = "locale_list.jsn";
    public static final String LOCAL_CITY = "Local City";
    public static final SimpleDateFormat LOG_DATE_FORMAT;
    public static final String LOG_FILE_NAME = "Log.txt";
    public static final int MAX_LIMIT = 5;
    public static final int MAX_NUM_OF_SPP_RETRIES = 3;
    public static final int MENU_EXIT = 2;
    public static final String MUSIC_CONTROLLER_TYPE_VALUE = "SERIAL";
    public static final int MUSIC_PHONE = 24;
    public static final int MUSIC_WD = 25;
    public static final int MetadataChangedInd = 32768;
    public static final int MicMuteReq = 11;
    public static final int MicMuteResp = 16395;
    public static final int MicUnmuteReq = 12;
    public static final int MicUnmuteResp = 16396;
    public static final int NORMAL_MODE = 1;
    public static final String NOTIFICATION_DATA = "app";
    public static final String NOTIFICATION_FILE_PATH = "/PHUB_NOTIFICATIONS";
    public static final String NOTIFICATION_SETTINGS_PREFS_FILE = "notification_settings_pref";
    public static final int NOTIFY_CONNECTED = 1;
    public static final int NUM_OF_RETRIES = 3;
    public static final long ONE_MINUTE_MILLISEC = 60000L;
    public static final String OPP_CONNECTION_TYPE = "btgoep://";
    public static final long OPP_TRANSFER_LOOPER_DELAY = 60000L;
    public static final String OPP_URL_PARAMETERS = ";authenticate=false;encrypt=false;master=false;android=true";
    public static String OPP_UUID_BASE = "00000001476D42C4BD119D377C456950";
    public static String PAYPHONE_NUMBER = "-3";
    public static final String PERSONALHUB_DEVICE_NAME[] = {
        "PHUB-WD", "Toq Smartwatch", "Toq Smar"
    };
    public static final String PERSONALHUB_LEFT_EAR_PIECE[] = {
        "PHUB-EP-L", "Toq L Headset", "ZolaHSL1", "ToqHSL1"
    };
    public static final String PERSONALHUB_RIGHT_EAR_PIECE[] = {
        "PHUB-EP-R", "Toq R Headset", "ZolaHSR1", "ToqHSR1"
    };
    public static final int PHUBSERVICE_APPID = 0;
    public static String PHUB_TCP_INTERFACE = "10.0.2.2";
    public static int PHUB_TCP_PORT = 0;
    public static final long POPUP_RESPONSE_WAIT_TIME = 10000L;
    public static final String POPUP_SHARED_PREFS_FILE = "popup_pref";
    public static final String PREFERENCES_EXPANDABLE_LIST_PREFS_FILE = "preferences_expandable_list_pref";
    public static String PRIVATE_NUMBER = "-2";
    public static final String PRODUCT_MODEL_EP = "ep_stretchboard1";
    public static final String PRODUCT_MODEL_EPL[] = {
        "ep_stretchboard1", "PHUB-EP-L", "Toq L Headset", "ZolaHSL1", "ToqHSL1", ""
    };
    public static final String PRODUCT_MODEL_EPR[] = {
        "ep_stretchboard1", "PHUB-EP-R", "Toq R Headset", "ZolaHSR1", "ToqHSR1", ""
    };
    public static final String PRODUCT_MODEL_EP_P2_BUILD_TARGET = "ep_p2";
    public static final String PRODUCT_MODEL_WD_A3 = "A3";
    public static final String PRODUCT_MODEL_WD_A3_BUILD_TARGET = "qt2_devboard3";
    public static final String PRODUCT_MODEL_WD_KAIROS_P0_BUILD_TARGET = "wd_kairos_p0";
    public static final String PRODUCT_MODEL_WD_KAIROS_SB_P1_BUILD_TARGET = "wd_kairos_sb_p1";
    public static final String PRODUCT_MODEL_WD_MASS_PRODUCTION = "MP";
    public static final String PRODUCT_MODEL_WD_P0 = "P0";
    public static final String PRODUCT_MODEL_WD_P1 = "P1";
    public static final String PRODUCT_MODEL_WD_P1_BUILD_TARGET = "wd_ffa_p1";
    public static final String PRODUCT_MODEL_WD_P2 = "P2";
    public static final String PRODUCT_MODEL_WD_P3 = "P3";
    public static final String PRODUCT_MODEL_WD_PILOT = "Pilot";
    public static final String PRODUCT_MODEL_WD_TOES_1_BUILD_TARGET = "wd_toes_1";
    public static final String PRODUCT_MODEL_WD_TOQ_2_BUILD_TARGET = "toq2_2";
    public static final String PRODUCT_MODEL_WD_TOQ_3_BUILD_TARGET = "toq2_3";
    public static final String PUSH_AIRPLANE_IMAGE_TYPE = "push_airplane_image";
    public static final String PUSH_DATA_ERROR_IMAGE_TYPE = "push_data_error_image";
    public static final String PUSH_OFFLINE_IMAGE_TYPE = "push_offline_image";
    public static final String PUSH_ONLINE_IMAGE_TYPE = "push_online_image";
    public static final int PauseReq = 2;
    public static final int PauseResp = 16386;
    public static final int PhoneStateInd = 32768;
    public static final int PlayListPlayReq = 7;
    public static final int PlayListPlayResp = 16391;
    public static final int PlayNextReq = 3;
    public static final int PlayNextResp = 16387;
    public static final int PlayPrevReq = 4;
    public static final int PlayPrevResp = 16388;
    public static final int PlayReq = 1;
    public static final int PlayResp = 16385;
    public static final int PlayStateChangedInd = 32769;
    public static final int PlaybackCompleteInd = 32770;
    public static final int PlayerDisconnectInd = 32772;
    public static final int PlayerStatusInd = 32771;
    public static final int PlayerStatusReq = 0;
    public static final int PlayerStatusResp = 16384;
    public static final int PopupInd = 32768;
    public static final String QUALCOMMTOQ_AMBIENT_UPGRADE_FILE = "qualcommtoq_ambient_upgrade_file";
    public static final String RELEASE = "release";
    public static final int REQUEST_CONNECT_DEVICE = 1;
    public static final int REQUEST_DISCOVERABLE_ENABLE_BT = 3;
    public static final int REQUEST_ENABLE_BT = 2;
    public static final int REQ_ACTION_DATE_CHANGED = 7;
    public static final int REQ_ACTION_UPDATE_ACTIVITY_DB = 8;
    public static final String REQ_CHECKSUM = "checksum";
    public static final int REQ_CONNECT_ANOTHER_DEVICE = 2;
    public static final String REQ_DIAL_NUMBER = "dial_number";
    public static final String REQ_FILE_PATH = "file_path";
    public static final String REQ_ITEM_ID = "item_id";
    public static final String REQ_POPUP_ID = "popup_id";
    public static final int REQ_RECONNECT = 1;
    public static final int REQ_SEND_MMS_DATA_TO_CONTROLLER = 5;
    public static final int REQ_SEND_SMS_DATA_TO_CONTROLLER = 4;
    public static final String REQ_SENT_FILE_NAME = "sent_file_name";
    public static final int REQ_SET_CALLER_NUMBER = 3;
    public static final String REQ_SILENCE_MODE = "silence_mode";
    public static final String REQ_SMS_PHONE_NUMBER = "phone_number";
    public static final String REQ_SMS_TEXT = "text";
    public static final String REQ_STORE = "store";
    public static final String REQ_TRANSACTION_ID = "transaction_id";
    public static final String REQ_TYPE = "type";
    public static final int REQ_UPDATE_ACTIVITY_PREFERENCE = 6;
    public static final String RESP_CALLER_ID = "caller_id";
    public static final String RESP_CALLER_ID_TYPE = "caller_id_type";
    public static final String RESP_CALLER_NAME = "caller_name";
    public static final String RESP_CALL_HELD = "call_held";
    public static final String RESP_CALL_SETUP_STATUS = "call_setup_status";
    public static final String RESP_CALL_STATUS = "call_status";
    public static final String RESP_CALL_TIME = "call_time";
    public static final String RESP_CHECKSUM = "checksum";
    public static final String RESP_CURRENT_TIME = "current time";
    public static final String RESP_DESCRIPTION = "description";
    public static final String RESP_FILENAME = "filename";
    public static final String RESP_FILE_PATH = "file_path";
    public static final String RESP_MIC_MUTE = "mic_mute";
    public static final String RESP_MUSIC_ALBUM = "album";
    public static final String RESP_MUSIC_ALBUM_ART = "album-art";
    public static final String RESP_MUSIC_ARTIST = "artist";
    public static final String RESP_MUSIC_CONTROLLER = "controller";
    public static final String RESP_MUSIC_PLAYER = "player";
    public static final String RESP_MUSIC_PLAYLIST = "playlist";
    public static final String RESP_MUSIC_STATE = "state";
    public static final String RESP_MUSIC_TITLE = "title";
    public static final String RESP_MUSIC_VERSION = "version";
    public static final String RESP_MUSIC_VOLUME_LEVEL = "volume_level";
    public static final String RESP_OPP = "OPP";
    public static final String RESP_POPUP_ID = "popup_id";
    public static final String RESP_RESULT = "result";
    public static final String RESP_SEQUENCE = "sequence";
    public static final String RESP_SERVICE = "service";
    public static final String RESP_STORE = "store";
    public static final String RESP_STORES = "stores";
    public static final String RESP_TIME = "time";
    public static final String RESP_TIME_DST = "dst";
    public static final String RESP_TIME_EPOCHTIME = "epoch_time";
    public static final String RESP_TIME_TIMEZONE = "time_zone";
    public static final String RESP_TRANSACTION_ID = "transaction_id";
    public static final String RESP_TRANSFER_MODE = "transfer_mode";
    public static final String RESP_VOLUME_LEVEL = "new_vol";
    public static final int RedialReq = 1;
    public static final int RedialResp = 16385;
    public static final int RejectCallReq = 6;
    public static final int RejectCallResp = 16390;
    public static final int ResetActivityCountReq = 1;
    public static final int ResetActivityCountResp = 16385;
    public static final int Return_Code_Bad_param = 4;
    public static final int Return_Code_General_Failure = 1;
    public static final int Return_Code_No_resources = 2;
    public static final int Return_Code_No_service = 3;
    public static final int Return_Code_Success = 0;
    public static final int RingInd = 32769;
    public static int SCREEN_HEIGHT = 0;
    public static int SCREEN_WIDTH = 0;
    public static final String SECONDARY_EP_STATUS = "SecondaryEPStatus";
    public static final String SERVICE_TASK = "service_task";
    public static final int SILENCE_MODE = 0;
    public static final String SILENCE_MODE_FLAG = "silence_mode";
    public static final int SMSReadIndication = 32769;
    public static final int SMS_MMS_PHONE = 3;
    public static final int SMS_MMS_WD = 4;
    public static final String SMS_SHARED_PREFS_FILE = "sms_pref";
    public static final int SPEECH_PHONE = 28;
    public static final int SPEECH_WD = 29;
    public static final int SPEED_DISPLAY_LIST_FAST = 350;
    public static final int SPEED_DISPLAY_LIST_MEDIUM = 500;
    public static final int SPEED_DISPLAY_LIST_SLOW = 750;
    public static final int SRC_ADDRESS[] = {
        0, 2, 4, 6, 8, 10, 16, 18, 20, 23, 
        25, 27, 29, 31, 33, 35
    };
    public static final int STATE_CONNECTED = 3;
    public static final int STATE_CONNECTING = 2;
    public static final int STATE_DISCONNECTED = 4;
    public static final int STATE_LISTEN = 1;
    public static final int STATE_NONE = 0;
    public static final long STOCK_AMBIENT_IDLE_THRESHOLD_MILLI = 0x36ee80L;
    public static final long STOCK_AMBIENT_POLL_INTERVAL_MILLI = 0xdbba0L;
    public static final String STOCK_LAST_UPDATE_TIME = "stock_last_update_time";
    public static final String STOCK_SYMBOLS = "StockSymbols";
    public static final String STOCK_SYMBOLS_BACKGROUND = "StockSymbolsBackGround";
    public static final String STOCK_SYMBOLS_BACKUP = "stock_symbol_backup";
    public static final String STOCK_SYMBOLS_COPY = "StockSymbolsCopy";
    public static final String STOCK_UPDATE_TIMESTAMP = "stock_update_timestamp";
    public static final String STORES_SHARED_PREFS_FILE = "stores_pref";
    public static final String STORE_AGENDA = "Phub.Phone.Agenda";
    public static final String STORE_ALL = "Phub.Phone.*";
    public static final String STORE_CLOCK_SETTINGS = "Phub.Phone.ClockSettings";
    public static final String STORE_COMM_HUB = "Phub.Phone.RecentComms";
    public static final String STORE_CONTACT = "Phub.Phone.Contacts";
    public static final String STORE_FAVORITE_APPS = "Phub.Phone.FavoriteApplets";
    public static final String STORE_JSON_FILE_PATH = "/PHUB_JSON";
    public static final String STORE_QUICK_REPLY = "Phub.Phone.Settings.QuickReply";
    public static final String STORE_USER_SETTINGS = "Phub.Phone.UserSettings";
    public static final int SYS_PHONE = 5;
    public static final int SYS_WD = 6;
    public static final int SecondayEPStatusInOperational = 5;
    public static final int SendSMSReq = 0;
    public static final int SendSMSResp = 16384;
    public static final int Service_Code_No_service = 0;
    public static final int Service_Code_Sevice_present = 1;
    public static final int SilencePhoneInd = 32769;
    public static final int SilencePhoneReq = 7;
    public static final int SilencePhoneResp = 16391;
    public static final int SpeakerVolumeDownReq = 10;
    public static final int SpeakerVolumeDownResp = 16394;
    public static final int SpeakerVolumeUpReq = 9;
    public static final int SpeakerVolumeUpResp = 16393;
    public static final int SpeechConvertedInd = 32768;
    public static final int SpeechStreamingCompleteReq = 0;
    public static final int SpeechStreamingCompleteResp = 16384;
    public static final int Speech_Status_Code_Ftp_Failed = 3;
    public static final int Speech_Status_Code_General_Failure = 1;
    public static final int Speech_Status_Code_Network_Error = 6;
    public static final int Speech_Status_Code_No_Conversion_Service = 4;
    public static final int Speech_Status_Code_No_Network_Connection = 2;
    public static final int Speech_Status_Code_Poor_Speech = 5;
    public static final int Speech_Status_Code_Success = 0;
    public static final int SwitchHeldAndCurrentCallReq = 8;
    public static final int SwitchHeldAndCurrentCallResp = 16392;
    public static final int SyncGetStoreStateReq = 0;
    public static final int SyncGetStoreStateResp = 16384;
    public static final int SyncStoreUpdatedInd = 32768;
    public static final int SyncUpdateStoreReq = 1;
    public static final int SyncUpdateStoreResp = 16385;
    public static final String TAKE_TOUR_SHARED_PREFS_FILE = "take_tour_prefs";
    public static final int TFTP_DEST_ADDRESS = 16;
    public static final int TFTP_PHONE = 15;
    public static final int TIME_DISPLAY_LIST_10 = 10;
    public static final int TIME_DISPLAY_LIST_20 = 20;
    public static final int TIME_DISPLAY_LIST_30 = 30;
    public static final String TIME_STAMP = "time_Stamp";
    public static final String TIME_ZONE = "GMT+00:00";
    public static final String TOAST = "toast";
    public static final String TOQ_HELP_LINK = "http://toq.qualcomm.com/app-help?utm_source=app&utm_medium=toq+app&utm_campaign=applink";
    public static final String TOQ_NOTIFICATION_ID_KEY = "notification_id_key";
    public static final String TOQ_NOTIFICATION_RECEIVER_NAME = "com.qualcomm.toq.smartwatch.ui.receiver.ToqNotificationReceiver";
    public static final String TOQ_SMARTWATCH_MAIN_ACTIVITY_CLASS_NAME = "com.qualcomm.toq.smartwatch.ui.activity.MainActivity";
    public static final String TOQ_SUPPORT_DEFAULT_EMAIL = "toq.support@qce.qualcomm.com";
    public static final String TOQ_VIDEO_LINK = "https://www.youtube.com/watch?v=Xc-qMtz8Qqw";
    public static final String TOQ_VIDEO_LINK_ID = "Xc-qMtz8Qqw";
    public static final int TOTAL_COMM_HUB_CONTACTS = 20;
    public static final int TOTAL_CONTACT_LIMIT = 3000;
    public static final int TOTAL_NUMBER_OF_CONTACTS = 2000;
    public static final String TRANSFER_TYPE = "OPP";
    public static final String TRUNK = "trunk";
    public static final long TWO_MINUTE_MILLISEC = 0x1d4c0L;
    public static final String TYPE_HOME = "Home";
    public static final String TYPE_MOBILE = "Mobile";
    public static final String TYPE_UNKNOWN = "Unknown";
    public static final String TYPE_WORK = "Work";
    public static final int TimeUpdateInd = 32768;
    public static final int TransferAudioToHFReq = 14;
    public static final int TransferAudioToHFResp = 16398;
    public static final int TransferAudioToPhoneReq = 13;
    public static final int TransferAudioToPhoneResp = 0x4000d;
    public static final int UNDEFINED = 0;
    public static final String UNDERSCORE_A = "_A";
    public static final String UNDERSCORE_B = "_B";
    public static String UNKNOWN_NUMBER = "-1";
    public static final String USAGE_LOG_APPENDER_NAME = "usagelog_appender";
    public static final String USAGE_LOG_FILE_NAME = "Usage_Log.txt";
    public static final String USAGE_LOG_TAG = "ToqUsageLog";
    public static final String USAGE_LOG_TYPE = "usage_log";
    public static final int UpdatePopupReq = 1;
    public static final int UpdatePopupResp = 16385;
    public static final String VER_IND_CONNECTED_EP = "connected_ep";
    public static final String VER_IND_EP_BASS_BOOST_MODE = "bass_boost_mode";
    public static final String VER_IND_EP_BASS_BOOST_STATUS = "bass_boost_status";
    public static final String VER_IND_EP_DOWLOADER_VERSION = "epdl_ota_version";
    public static final String VER_IND_LINK_KEY = "link_key_ep";
    public static final String VER_IND_MODE = "mode";
    public static final String VER_IND_MODE_CONFIG = "Config";
    public static final String VER_IND_MODE_OPERATIONAL = "Operational";
    public static final String VER_IND_ROLE = "role";
    public static final String VER_IND_ROLE_PRIMARY = "Primary";
    public static final String VER_IND_ROLE_SECONDARY = "Secondary";
    public static final int VIBE_REAPEAT_1 = 1;
    public static final int VIBE_REAPEAT_2 = 2;
    public static final int VIBE_REAPEAT_3 = 3;
    public static final int VIBE_REAPEAT_4 = 4;
    public static final int VIBE_REAPEAT_NONE = 0;
    public static final int VIBE_STYLE_A = 0;
    public static final int VIBE_STYLE_B = 1;
    public static final int VIBE_STYLE_C = 2;
    public static final int VIBE_STYLE_D = 3;
    public static final int VOICE_PHONE = 1;
    public static final int VOICE_WD = 2;
    public static final int VersionInd = 0;
    public static final int VoiceCommandReq = 10;
    public static final int VoiceCommandResp = 16394;
    public static final int VolumeDownReq = 6;
    public static final int VolumeDownResp = 16390;
    public static final int VolumeUpReq = 5;
    public static final int VolumeUpResp = 16389;
    public static final String WATCH_DETAILS_PREFS_FILE = "watch_details_pref";
    public static final long WD_BATTERY_LEVEL_QUERY_INTERVAL = 0x1499700L;
    public static final String WD_STOCK_APP_IMAGE_PATH = "/apps/stock/";
    public static final String WD_STOCK_PATH = "/ad/stock/";
    public static final String WD_WEATHER_APP_IMAGE_PATH = "/apps/weather/";
    public static final String WD_WEATHER_PATH = "/ad/weather/";
    public static final long WEATHER_AMBIENT_IDLE_THRESHOLD_MILLI = 0x1499700L;
    public static final long WEATHER_AMBIENT_POLL_INTERVAL_MILLI = 0x2932e0L;
    public static final String WEATHER_CITIES = "WeatherCities";
    public static final String WEATHER_CITIES_BACKGROUND = "WeatherCitiesBackGround";
    public static final String WEATHER_CITIES_COPY = "WeatherCitiesCopy";
    public static final String WEATHER_CITIES_TEMPERATURE_UNIT_CHANGED = "weather_cities_temp_unit_changed";
    public static final String WEATHER_CITY_BACKUP = "weather_city_backup";
    public static final String WEATHER_CURRENT_CITY = "WeatherCurrentCity";
    public static final String WEATHER_CURRENT_CITY_UPDATE = "WeatherCurrentCityUpdate";
    public static final String WEATHER_LAST_UPDATE_TIME = "weather_last_update_time";
    public static final String WEATHER_TIMER_INTERVAL = "weather_timer_interval";
    public static final String WEATHER_UNIT_OF_TEMPERATURE = "weather_temperature_unit";
    public static final String WEATHER_UPDATE_TIMESTAMP = "weather_update_timestamp";
    public static final String WEEK_BAR_CHART_TYPE = "week_bar_chart";
    public static final String WORLD_CLOCK_APP_ZIP_ASSET_NAME = "worldclock_app.zip";
    public static final String WORLD_CLOCK_CITIES_DAT = "cities.dat";
    public static final String WORLD_CLOCK_CITIES_DAT_LOCATION = "/res/apps/cities.dat";
    public static final String WORLD_CLOCK_ICON_A = "icon_A.img";
    public static final String WORLD_CLOCK_ICON_B = "icon_B.img";
    public static final String WORLD_CLOCK_IMAGE_FOLDER = "images";
    public static final int WORLD_CLOCK_IMAGE_LIMIT = 2;
    public static final String WORLD_CLOCK_TEMP_A = "temp_A.img";
    public static final String WORLD_CLOCK_TEMP_B = "temp_B.img";
    public static final String WORLD_CLOCK_TYPE = "WorldClock";
    public static final String WORLD_CLOCK_ZIP_LOCATION = "/packages/com.qualcomm.qce.worldclock/ClockWorld.zip";
    public static final String WORLD_CLOCK_ZIP_NAME = "ClockWorld.zip";
    public static ArrayList appList = new ArrayList();
    public static ArrayList appListIcon = new ArrayList();
    public static final String appletImageNames[] = {
        "Comm Hub", "Weather", "Calendar", "Stocks", "Music", "Status", "Activity", "Notifications", "Alarm"
    };
    public static final String appletWDNames[] = {
        "CommsHub", "Weather", "Agenda", "Stocks", "MediaControl", "Status", "Activity", "com.qualcomm.qce.androidnotifications/Notifications", "com.qualcomm.qce.alarmclock/AlarmClock"
    };
    public static final int bassBoostRequest = 6;
    public static final int bassBoostResponse = 7;
    public static ArrayList commsHistoryValue = new ArrayList();
    public static final String iconImagesText[] = {
        "Optima", "Luminous", "Solar", "Vibrant", "Aurora", "Innova"
    };
    public static boolean isChangeRolesActive = false;
    public static ArrayList phList = new ArrayList();
    public static ArrayList phListIcon = new ArrayList();
    public static ArrayList qrList = new ArrayList();
    public static final CharSequence syncScheduleItems[] = {
        "Auto", "1 hour", "2 hour", "Waking from sleep mode"
    };


    public static void setCommsHistoryValue()
    {
        commsHistoryValue.clear();
        commsHistoryValue.add(Integer.valueOf(10));
        commsHistoryValue.add(Integer.valueOf(20));
        commsHistoryValue.add(Integer.valueOf(30));
        commsHistoryValue.add(Integer.valueOf(40));
    }

    public static void setListValues()
    {
        phList.clear();
        phList.add(Integer.valueOf(0x7f0a0026));
        phList.add(Integer.valueOf(0x7f0a0027));
        phList.add(Integer.valueOf(0x7f0a0013));
        phList.add(Integer.valueOf(0x7f0a0014));
        phList.add(Integer.valueOf(0x7f0a0015));
        phList.add(Integer.valueOf(0x7f0a0016));
        phListIcon.clear();
        phListIcon.add(Integer.valueOf(0x7f02011d));
        phListIcon.add(Integer.valueOf(0x7f02011f));
        phListIcon.add(Integer.valueOf(0x7f02011c));
        phListIcon.add(Integer.valueOf(0x7f02011b));
        phListIcon.add(Integer.valueOf(0x7f02011e));
        phListIcon.add(Integer.valueOf(0x7f020120));
        qrList.clear();
        qrList.add(Integer.valueOf(0x7f0a0031));
        qrList.add(Integer.valueOf(0x7f0a0032));
        qrList.add(Integer.valueOf(0x7f0a0033));
        qrList.add(Integer.valueOf(0x7f0a0034));
        qrList.add(Integer.valueOf(0x7f0a0035));
        qrList.add(Integer.valueOf(0x7f0a0036));
    }

    static 
    {
        APPLICATION_PACKAGE_NAME = "com.qualcomm.toq";
        FTP_STANDARD_UUID = "0000110600001000800000805f9b34fb";
        FTP_UUID = FTP_STANDARD_UUID;
        ACTION_ACTIVITY_MONITORING_UPDATE = (new StringBuilder()).append(APPLICATION_PACKAGE_NAME).append(".smartwatch.activity_monitoring.update").toString();
        LOG_DATE_FORMAT = new SimpleDateFormat("MMM d, yyyy HH:mm:ss ZZZZ", Locale.US);
        ACTION_CONNECTION_STATE_CHANGE = (new StringBuilder()).append(APPLICATION_PACKAGE_NAME).append(".base.connection_state_changed").toString();
        ACTION_ALOHA_STATE_CHANGE = (new StringBuilder()).append(APPLICATION_PACKAGE_NAME).append(".smartwatch.aloha_state_changed").toString();
        ACTION_BLUETOOTH_NOT_SUPPORTED = (new StringBuilder()).append(APPLICATION_PACKAGE_NAME).append(".smartwatch.bluetooth_not_supported").toString();
        ACTION_BLUETOOTH_NOT_ENABLED = (new StringBuilder()).append(APPLICATION_PACKAGE_NAME).append(".smartwatch.bluetooth_not_enabled").toString();
        ACTION_ASSOCIATE_WD_DEVICE = (new StringBuilder()).append(APPLICATION_PACKAGE_NAME).append(".smartwatch.associate_wd_device").toString();
        ACTION_EAR_PIECE_CONNECTED = (new StringBuilder()).append(APPLICATION_PACKAGE_NAME).append(".smartwatch.earpiece.connected").toString();
        ACTION_EAR_PIECE_DISCONNECTED = (new StringBuilder()).append(APPLICATION_PACKAGE_NAME).append(".smartwatch.earpiece.disconnected").toString();
        ACTION_EAR_PIECE_UI_UPDATE = (new StringBuilder()).append(APPLICATION_PACKAGE_NAME).append(".smartwatch.earpiece.update").toString();
        ACTION_CALL_STATE_RINGING = (new StringBuilder()).append(APPLICATION_PACKAGE_NAME).append(".smartwatch.phone.ringing").toString();
        ACTION_CALL_STATE_IDLE = (new StringBuilder()).append(APPLICATION_PACKAGE_NAME).append(".smartwatch.phone.idle").toString();
        ACTION_CALL_STATE_OFF_HOOK = (new StringBuilder()).append(APPLICATION_PACKAGE_NAME).append(".smartwatch.phone.offhook").toString();
        ACTION_INSTALLED_ADDON_APP = (new StringBuilder()).append(APPLICATION_PACKAGE_NAME).append(".smartwatch.installed_addon_app").toString();
        ACTION_UNINSTALLED_ADDON_APP = (new StringBuilder()).append(APPLICATION_PACKAGE_NAME).append(".smartwatch.uninstalled_addon_app").toString();
        ACTION_REMOTE_DEVICE_DISASSOCIATED = (new StringBuilder()).append(APPLICATION_PACKAGE_NAME).append(".smartwatch.remote_device_disassociated").toString();
        ACTION_WD_DEVICE_DISASSOCIATED = (new StringBuilder()).append(APPLICATION_PACKAGE_NAME).append(".smartwatch.wd_device_disassociated").toString();
        ACTION_CANCEL_FIND_PHONE_REQUEST = (new StringBuilder()).append(APPLICATION_PACKAGE_NAME).append(".smartwatch.cancel_find_phone_request").toString();
        ACTION_FOUND_WD_REQUEST = (new StringBuilder()).append(APPLICATION_PACKAGE_NAME).append(".smartwatch.found_wd_request").toString();
        ACTION_CONNECTION_STOPPED = (new StringBuilder()).append(APPLICATION_PACKAGE_NAME).append(".smartwatch.connection.stopped").toString();
        ACTION_SERVICE_STOPPED = (new StringBuilder()).append(APPLICATION_PACKAGE_NAME).append(".smartwatch.service.stopped").toString();
        ACTION_VERSION_INFO = (new StringBuilder()).append(APPLICATION_PACKAGE_NAME).append(".smartwatch.version.info").toString();
        ACTION_FIRMWARE_TRANSFER = (new StringBuilder()).append(APPLICATION_PACKAGE_NAME).append(".smartwatch.firmware.transfer").toString();
        ACTION_FIRMWARE_TRANSFER_PROGRESS = (new StringBuilder()).append(APPLICATION_PACKAGE_NAME).append(".smartwatch.firmware.transfer.progress").toString();
        ACTION_SMARTWATCH_HANDLE_MESSAGE_SERVICE = (new StringBuilder()).append(APPLICATION_PACKAGE_NAME).append(".smartwatch.connectionmanager.bluetooth.receiver.HandleMessageService").toString();
        ACTION_EAR_PIECE_HANDLE_MESSAGE_SERVICE = (new StringBuilder()).append(APPLICATION_PACKAGE_NAME).append(".earpiece.connectionmanager.bluetooth.receiver.HandleMessageService").toString();
        ACTION_SPP_MESSAGE_ERROR = (new StringBuilder()).append(APPLICATION_PACKAGE_NAME).append(".smartwatch.message.error").toString();
        ACTION_SMARTWATCH_APP_UPDATED = (new StringBuilder()).append(APPLICATION_PACKAGE_NAME).append(".smartwatch.app_updated").toString();
        ACTION_SMARTWATCH_FMS_FILE_SYNCED = (new StringBuilder()).append(APPLICATION_PACKAGE_NAME).append(".smartwatch.fms.file_synced").toString();
        ACTION_SMARTWATCH_VOLUME_MUSIC = (new StringBuilder()).append(APPLICATION_PACKAGE_NAME).append(".smartwatch.music.VOLUME").toString();
        ACTION_SMARTWATCH_CANCEL_ALL_NOTIFICATION = (new StringBuilder()).append(APPLICATION_PACKAGE_NAME).append(".smartwatch.cancel.all.notification").toString();
        ACTION_SMARTWATCH_CANCEL_NOTIFICATION = (new StringBuilder()).append(APPLICATION_PACKAGE_NAME).append(".smartwatch.cancel.notification").toString();
        PHUB_TCP_PORT = 5000;
        ACTION_FMS_FILE_TRANSFER_COMPLETED = (new StringBuilder()).append(APPLICATION_PACKAGE_NAME).append(".smartwatch.fms.transfer_complete").toString();
        ACTION_PHONE_WD_CONNECTED = (new StringBuilder()).append(APPLICATION_PACKAGE_NAME).append(".smartwatch.wd_connected").toString();
        ACTION_PHONE_WD_DISCONNECTED = (new StringBuilder()).append(APPLICATION_PACKAGE_NAME).append(".smartwatch.wd_disconnected").toString();
        ACTION_FMS_FILE_TRANSFER_FAILED = (new StringBuilder()).append(APPLICATION_PACKAGE_NAME).append(".smartwatch.fms.transfer_failure").toString();
        ACTION_EP_CONFIG_STATE_UPDATE = (new StringBuilder()).append(APPLICATION_PACKAGE_NAME).append(".earpiece.state_update").toString();
        ACTION_EP_MORE_HEADSETS_FOUND_UPDATE = (new StringBuilder()).append(APPLICATION_PACKAGE_NAME).append(".earpiece.more_headsets_found_update").toString();
        ACTION_EAR_PIECE_PROFILE_UPDATE = (new StringBuilder()).append(APPLICATION_PACKAGE_NAME).append(".earpiece.profile_update").toString();
        A2DP_PROFILE_CONNECTED = (new StringBuilder()).append(APPLICATION_PACKAGE_NAME).append(".earpiece.a2dp_profile_connected").toString();
        A2DP_PROFILE_DISCONNECTED = (new StringBuilder()).append(APPLICATION_PACKAGE_NAME).append(".earpiece.a2dp_profile_disconnected").toString();
        HFP_PROFILE_CONNECTED = (new StringBuilder()).append(APPLICATION_PACKAGE_NAME).append(".earpiece.hfp_profile_connected").toString();
        HFP_PROFILE_DISCONNECTED = (new StringBuilder()).append(APPLICATION_PACKAGE_NAME).append(".earpiece.hfp_profile_disconnected").toString();
        ACTION_NEW_LOCATION_FOUND = (new StringBuilder()).append(APPLICATION_PACKAGE_NAME).append(".smartwatch.ACTION_NEW_LOCATION_FOUND").toString();
        ACTION_INITIATE_CALL = (new StringBuilder()).append(APPLICATION_PACKAGE_NAME).append(".smartwatch.initiate_call").toString();
        ACTION_CANCEL_CALL = (new StringBuilder()).append(APPLICATION_PACKAGE_NAME).append(".smartwatch.cancel_call").toString();
    }
}
